src/main/java/com/soda/common/BaseEntity.java
src/main/java/com/soda/request/service/RequestService.java

- 데이터 수정시에 `createdAt`이 업데이트 되는 버그 해결하였습니다.
Closed #16 
- `BaseEntity`의 `createdAt`필드에 `@Column(updatable = false)`를 달았음.
- 데이터 생성시에 `updatedAt`은 `createdAt`과 동일하게 업데이트되는게 정상적인 동작이라고합니다.
- 데이터 수정시에는 `updatedAt`만 업데이트됩니다.

fix: 데이터 수정시에도 createdAt이 업데이트 되는 버그 해결

---

src/main/java/com/soda/global/security/auth/UserDetailsImpl.java
src/main/java/com/soda/global/security/jwt/JwtAuthenticationFilter.java

JwtAuthenticationFilter에서 인증된 사용자의 ID와 역할을 HTTP 요청 속성(request attribute)으로 추가하여, 
컨트롤러에서 해당 정보를 쉽게 접근하고 사용할 수 있도록 수정했습니다. 
기존에는 @AuthenticationPrincipal 어노테이션을 통해 사용자 정보를 받았지만,
필터에서 직접 요청 속성에 정보를 추가함으로써 컨트롤러에서 보다 유연하고 안전하게 
사용자 정보를 활용할 수 있게 되었습니다.
1.  **유연성 향상**: 컨트롤러에서 `UserDetails` 객체에 직접 의존하지 않고 필요한 사용자 정보만 요청 속성에서 가져올 수 있습니다.
2.  **추가 정보 활용**: `UserDetails` 객체에서 제공하지 않는 추가적인 사용자 정보를 요청 속성에 추가하여 컨트롤러에서 활용할 수 있습니다.
3.  **테스트 용이성**: 단위 테스트 작성 시 요청 속성을 쉽게 모킹할 수 있습니다.
4.  **보안 강화**: 요청 속성은 서버 내부에서만 접근 가능하므로 헤더보다 안전하게 사용자 정보를 전달할 수 있습니다.
5.  **코드 간결성**: 컨트롤러에서 사용자 정보를 추출하는 코드가 간결해져 코드의 가독성과 유지보수성이 향상됩니다.
```java
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController; …
```

[Feature] JwtAuthenticationFilter에서 사용자정보를 요청 속성으로 추가

---

src/main/java/com/soda/common/BaseEntity.java
src/main/java/com/soda/common/CustomAuditingEntityListener.java
src/main/java/com/soda/common/TrackUpdate.java
src/main/java/com/soda/request/entity/Request.java

- `updatedAt` 원하는 필드 변경시에만 변경되게 리팩토링
Closed #29 
- 기존 `BaseEntity`가 `AuditingEntityListener`를 EventListen하는 구조에서 `CustomAuditingEntityListener`를 EventListen하는 구조로 변경
- `CustomAuditingEntityListener`에서 `@TrackUpdate` 애너테이션이 붙어있는 필드가 변경될 때만 `updatedAt`이 업데이트 되도록 로직을 짰습니다.
- `@TrackUpdate`애너테이션도 수동으로 작성하였습니다
- 이제 `updatedAt`이 업데이트되길 원하는 필드에 `@TrackUpdate` 애너테이션을 붙이면 해당 필드가 변경될 때만 `updatedAt`이 변경되게 됩니다.
```java
@Entity
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Getter
public class Request extends BaseEntity {
@Enumerated(EnumType.STRING)
private RequestStatus status;
@TrackUpdate
private String title;
@TrackUpdate
@Lob
private String content;
```

[Refactor] updatedAt 원하는 필드 변경시에만 변경되게 리팩토링

---

src/main/java/com/soda/global/response/CommonErrorCode.java
src/main/java/com/soda/global/security/auth/UserDetailsServiceImpl.java
src/main/java/com/soda/global/security/jwt/JwtAuthenticationFilter.java
src/main/java/com/soda/member/error/AuthErrorCode.java
src/main/java/com/soda/member/error/CompanyErrorCode.java
src/main/java/com/soda/member/error/MemberErrorCode.java
src/main/java/com/soda/member/service/AuthService.java
src/main/java/com/soda/member/service/CompanyService.java
src/main/java/com/soda/request/service/RequestService.java

- MemberErrorCode: 멤버 관련 에러 코드 관리
- CompanyErrorCode: 회사 관련 에러 코드 관리
- AuthErrorCode: 인증 관련 에러 코드 관리
- AuthService, CompanyService에서 분리된 도메인별 에러 코드를 사용하도록 수정
- 예외 처리 개선 및 명확한 예외 메시지 추가
- 에러 코드 수정 및 로그 메시지 개선
#35

[Refactor] ErrorCode Enum 분리 (Member, Company, Auth)

---

src/main/java/com/soda/article/controller/ArticleController.java
src/main/java/com/soda/article/domain/article/ArticleCreateResponse.java
src/main/java/com/soda/article/entity/ArticleFile.java
src/main/java/com/soda/article/error/ArticleErrorCode.java
src/main/java/com/soda/article/strategy/ArticleFileStrategy.java
src/main/java/com/soda/request/strategy/RequestFileStrategy.java
src/main/java/com/soda/request/strategy/ResponseFileStrategy.java

게시글 파일 첨부/삭제 기능 개발
Closed #58 
- ArticleFileStrategy(게시글 파일 전략패턴 구현체 작성)
- ArticleFile이 Filebase라는 추상클래스를 상속받게하고 구현해야할 추상메서드를 구현
- ArticleController에 파일 첨부/삭제 API 구현
- 파일 업로드 테스트중 Article POST시 500상태코드가 반환되는 에러가 발생했었는데, ArticleCreateResponse에서 article의 parentArticleId가 null인데 get하려고 해서 발생한 문제였습니다. 삼항연산자로 null일 때 반환값 처리를 해주어 해결하였습니다.

[Feature] 게시글 파일 첨부/삭제 기능 개발

---

src/main/java/com/soda/member/service/CompanyService.java
src/main/java/com/soda/member/service/MemberService.java
src/main/java/com/soda/project/service/CompanyProjectService.java
src/main/java/com/soda/project/service/MemberProjectService.java
src/main/java/com/soda/project/service/ProjectService.java

Project service 로직에서 repository를 참조하지 않고 service를 참조하도록 개인 리팩토링을 진행하였습니다,
#57 
- 객체에 적절한 책임을 부여해 결합도를 낮추고 응집도를 높여 변경에 용이한 시스템을 구성하기 위해 companyProject, memberProject 관련 로직들을 전부 각각 service 파일로 분리했습니다.
- `getCompany()`는 id로 회사를 조회하는 메서드입니다.
- 이를 통해 반복회는 코드를 줄이고 project service 쪽에서도 참조 가능하도록 변경하였습니다.
- 멤버 관련 로직을 MemberService에 따로 분리하였습니다.

[Refactor] Project Service 리팩토링

---

src/main/java/com/soda/project/service/CompanyProjectService.java
src/main/java/com/soda/project/service/ProjectService.java

Project, CompanyProject 순환 참조 오류 해결
closes #61 
- 기존 로직을 보면 CompanyProjectService에서 ProjectService를 참조하면서 순환참조 오류가 발생했습니다.
```
public void assignCompanyToProject(Long companyId, Long projectId, CompanyProjectRole role) {
Company company = companyService.getCompany(companyId);
Project project = projectService.getProjectById(projectId);
if (!company.getIsDeleted() && !companyProjectRepository.existsByCompanyAndProject(company, project)) {
CompanyProjectDTO companyProjectDTO = CompanyProjectDTO.builder()
.companyId(company.getId())
.projectId(project.getId())
.companyProjectRole(role)
.build();
// DTO -> Entity
CompanyProject companyProject = companyProjectDTO.toEntity(company, project, role);
// 데이터베이스에 회사-프로젝트 관계 저장
companyProjectRepository.save(companyProject);
}
}
```
- 그래서 Project를 id로 …

[hotfix] 순환참조 에러 해결

---

src/main/java/com/soda/member/dto/MemberUpdateRequest.java
src/main/java/com/soda/member/dto/SignupRequest.java
src/main/java/com/soda/member/entity/Member.java
src/main/java/com/soda/member/error/AuthErrorCode.java
src/main/java/com/soda/member/repository/CompanyRepository.java
src/main/java/com/soda/member/repository/MemberRepository.java
src/main/java/com/soda/member/service/AuthService.java
src/main/java/com/soda/member/service/CompanyService.java
src/main/java/com/soda/member/service/MemberService.java
src/main/java/com/soda/project/service/StageService.java
src/main/java/com/soda/project/service/TaskService.java

테스트 용이성을 높이고 "서비스당 레파지토리 하나" 원칙을 준수하기 위해 AuthService, MemberService, CompanyService 관련 코드를 리팩토링했습니다.
- **AuthService 수정:**
- **`MemberRepository` 직접 참조 제거:** 기존에 `MemberRepository`를 직접 사용하던 로직을 **`MemberService`를 호출**하는 방식으로 변경하여 "서비스당 레파지토리 하나" 원칙을 준수하도록 수정했습니다. 
- 기존에 `CompanyRepository`를 직접 참조하던 로직을 `CompanyService` 호출 방식으로 변경했습니다.
- 중복 로직을 분리하여 코드 가독성을 개선했습니다. 
- **MemberService 수정:**
- `AuthService`에서 필요로 하는 회원 관련 조회/수정 로직을 처리하는 메소드를 추가했습니다.
- `AuthService`에서 이관된 회원 정보 수정 기능을 포함하여 일반적인 회원 관리 책임을 담당합니다.
- 다른 서비스(ProjectService 등)에서 Member 정보를 필요로 할 경우 사용할 수 있는 조회 메소드를 추가했습니다. 
- **CompanyService 리팩토링:**
- Company 도메인 관련 로직에 집중하도록 수정하고, 다른 서비스에서 필요로 하는 조회 메소드를 추가했습니다. 
- **ErrorCode 추가:** 리팩토링 과정에서 필요한 ErrorCode를 추가했습니다. 
이번 리팩토링을 통해 각 서비스의 책임을 명확히 하고, 정해진 "서비스당 레파지토리 하나" 설계 원칙을 …

[Refactor] Member, Company 리팩토링

---

src/main/java/com/soda/article/domain/article/ArticleCreateRequest.java
src/main/java/com/soda/article/domain/article/ArticleModifyRequest.java
src/main/java/com/soda/article/service/ArticleService.java
src/main/java/com/soda/member/dto/LoginRequest.java
src/main/java/com/soda/request/controller/RequestController.java
src/main/java/com/soda/request/controller/ResponseController.java
src/main/java/com/soda/request/dto/response/RequestApproveRequest.java
src/main/java/com/soda/request/dto/response/RequestRejectRequest.java
src/main/java/com/soda/request/dto/response/ResponseUpdateRequest.java
src/main/java/com/soda/request/entity/Response.java
src/main/java/com/soda/request/entity/ResponseFile.java
src/main/java/com/soda/request/service/RequestService.java
src/main/java/com/soda/request/service/ResponseService.java
src/main/java/com/soda/request/strategy/ResponseFileStrategy.java
src/main/java/com/soda/request/strategy/ResponseLinkStrategy.java

- Article, Request, Response 생성/수정 API 호출 시 파일 업로드가 불가하게 하였습니다.
- 개별 파일(다중)업로드하는 API를 호출하는 방식으로 수정하였습니다.
#74
- Request, Response는 LinkService, FileService를 이용해 코드 작성하였는데,
차후 전략패턴을 폐기할 수도 있어 Article은 우선 기존 코드 주석처리하는 방식으로만 작업하였습니다.
차후 전략패턴을 폐기하고 단순화한 다음에 작업할 예정입니다.

[Refact] 파일 업로드 분리

---

src/main/java/com/soda/article/domain/article/ArticleCreateRequest.java
src/main/java/com/soda/article/domain/article/ArticleModifyRequest.java
src/main/java/com/soda/article/entity/Article.java
src/main/java/com/soda/article/entity/ArticleFile.java
src/main/java/com/soda/article/entity/ArticleLink.java
src/main/java/com/soda/article/service/ArticleLinkService.java
src/main/java/com/soda/article/service/ArticleService.java
src/main/java/com/soda/article/strategy/ArticleFileStrategy.java
src/main/java/com/soda/article/strategy/ArticleLinkStrategy.java

- Article에 Link/File 전략패턴 적용 
- 생성/수정시 링크 다중 삽입 가능하게 적용
#56  #74 
- 전략패턴이 Request와 Response에만 적용돼있었는데 Article에도 적용함.
- 차후 전략패턴을 폐기할 수도 있지만 우선은 시스템의 일관성을 위해 Article에도 적용하였음.
- 서연님이 작성하셨던 ArticleCreate, ArticleUpdate하는 메서드에서 링크,파일부분 수정하였습니다. 살펴보시고 말씀해주세요..!!

🚧  [Refact] Article에 Link/File 전략패턴 적용 및 생성/수정시 링크 다중 삽입 가능하게 적용

---

build.gradle
src/main/java/com/soda/SodaApplication.java
src/main/java/com/soda/global/log/LogController.java
src/main/java/com/soda/global/log/LogInfo.java
src/main/java/com/soda/global/log/LogRepository.java
src/main/java/com/soda/global/log/LogService.java
src/main/resources/application.yml

- 몽고 DB 연결 및 몽고DB의 데이터가 잘 조회되는지 테스트하는 API 구현하였습니다.
#78 
- 데이터 생성/수정/삭제 로그를 쌓아야하는데 엔티티마다 필드가 달라 RDB보다는 NoSQL이 적합함.
- 몽고DB와 Elasticsearch를 고민하였지만, 현재 시스템의 크기로서는 몽고DB가 적합하다고 생각하였음. 차후 시스템이 확장되고 로그량이 많아지면 Elasticsearch로 이관하는 방안도 고려해볼 수 있을 것 같음.
- 몽고DB Atlas라는 클라우드 db를 사용함.
- AWS RDS로 MySQL을 사용하는 것과 유사함.
- 엔드포인트 따로 전달드리겠습니다.
- .env파일이 업데이트되어 따로 전달드리겠습니다

[Feature] 몽고DB 연결

---

src/main/java/com/soda/project/domain/ProjectListResponse.java
src/main/java/com/soda/project/domain/ProjectResponse.java
src/main/java/com/soda/project/service/ProjectService.java

프론트와 연동 시 response에 id가 존재하지 않아 연동이 되지 않는 오류를 해결하기 위해 response를 수정했습니다.
closes #85 
- response에 id를 추가하였습니다.

[fix] 조회 시 id 없는 버그 해결

---

src/main/java/com/soda/project/domain/stage/StageReadResponse.java

프론트와 연동 시 StageReadResponse에 task 정보를 추가했습니다.
#87

[fix]: StageReadResponse 조회시 task정보 추가

---

src/main/java/com/soda/article/domain/article/ArticleCreateResponse.java
src/main/java/com/soda/article/domain/article/ArticleViewResponse.java
src/main/java/com/soda/article/domain/comment/CommentDTO.java
src/main/java/com/soda/article/repository/CommentRepository.java
src/main/java/com/soda/article/service/CommentService.java

프론트와 연동 시 발생한 오류를 해결했습니다.
closed #90 
- createdAt이 없어서 최신순 조회가 안되고 있어서 추가했습니다.
- 관리자/해당 프로젝트 참여자만 조회 가능한 경우로 로직 수정했습니다.
- 댓글 조회 시, 삭제된 부모 댓글이 존재하는 경우 자식 댓글들이 조회가 되지 않는 오류가 발생했습니다.
- 그래서 전체 조회되도록 repository 코드를 수정하고, response에 delete를 추가했습니다.
- 프론트에서는 delete treu인 댓글은 제외되도록 예외처리하고 연동하였습니다.

[Fix] Article, Comment API 연동 시 오류 해결

---

src/main/java/com/soda/article/controller/ArticleController.java
src/main/java/com/soda/request/controller/RequestController.java
src/main/java/com/soda/request/controller/ResponseController.java
src/main/java/com/soda/request/dto/request/RequestDTO.java
src/main/java/com/soda/request/dto/response/ResponseDTO.java

- 링크, 파일 삭제가 되지 않는 버그 해결
- 링크,파일 조회시 isDeleted==true인 링크,파일도 조회되는 버그 해결
#92 
- 링크, 파일 삭제하는 메서드 호출 시 파라미터 순서를 잘못 넣어 삭제가 되지 않아 이를 모두 고쳤습니다.
- Article, Request, Response 모두 고침
- Request, Response에서 파일, 링크 조회할 때 isDeleted==false인 파일, 링크만 조회되게 수정하였습니다

[Fix] 링크,파일 관련 오류 해결

---

src/main/java/com/soda/article/domain/article/ArticleListViewResponse.java
src/main/java/com/soda/article/repository/ArticleRepository.java
src/main/java/com/soda/article/service/ArticleService.java

게시글 전체 조회 시 삭제된 게시글 조회 되지 않도록 수정하였습니다.
closes #105 
- 부모 게시글이 삭제되었어도 자식 게시글을 조회하기 위하여 로직을 수정했습니다.
- response에 `boolean isDeleted`를 추가하여 삭제 여부를 판단할 수 있도록 하였습니다.
- `isDeletedFalse` 삭제하고 전체 게시글을 조회한 다음 프론트 단에서 삭제된 게시글을 조회할 수 없도록 수정하였습니다.

[Fix] 게시글 전체 조회 오류 수정

---

src/main/java/com/soda/global/config/SwaggerConfig.java
src/main/java/com/soda/member/controller/MemberController.java
src/main/java/com/soda/member/dto/InitialUserInfoRequestDto.java
src/main/java/com/soda/member/dto/member/LoginResponse.java
src/main/java/com/soda/member/entity/Member.java
src/main/java/com/soda/member/service/AuthService.java
src/main/java/com/soda/member/service/MemberService.java

사용자가 최초 로그인 후 필수 프로필 정보(이름, 이메일, 전화번호, 아이디, 비밀번호, 직책 등)를 설정하는 기능을 구현했습니다. 
이와 함께 로그인 응답에 사용자 ID를 추가하고, 관리자 사용자 생성 관련 오류 및 Swagger 설정을 수정했습니다.
1.  **사용자 초기 프로필 설정 기능 추가:**
*   사용자가 필수 정보를 입력하여 초기 프로필을 설정하는 API 를 구현했습니다 
*   초기 설정 요청을 처리하기 위한 DTO (`InitialUserInfoRequestDto`)를 생성했습니다.
*   프로필 정보를 업데이트하는 서비스 로직 (`MemberService.setupInitialProfile`)을 구현했습니다.
*   `Member` 엔티티에 초기 프로필 정보를 한 번에 업데이트하는 `initialProfile` 메소드를 추가했습니다.
2.  **로그인 응답 수정:**
*   로그인 성공 시 반환되는 `LoginResponse` DTO에 `memberId` 필드를 추가하여, 클라이언트에서 사용자 식별이 용이하도록 개선했습니다.
3.  **관리자 사용자 생성 로직 수정:**
*   관리자(ADMIN) 역할의 사용자를 생성할 때, 회사 ID(`companyId`)가 제공되더라도 실제로는 회사 정보를 연결하지 않도록 `AuthService.signup` 로직을 수정하여 관련 오류를 해결했습니다.
4.  **Swagger 설정 수정:**
*   `SwaggerConfig`에서 API 서버 주소(`servers` 설정)를 명시적으로 설정하여 배포 환경에서의 Swagger UI 동작을 개선했습니다. …

[Feature] 첫 로그인 사용자 정보 업데이트 API 개발 및 사용자 관련 오류 수정

---

src/main/java/com/soda/global/config/SwaggerConfig.java
src/main/java/com/soda/member/controller/MemberController.java
src/main/java/com/soda/member/dto/InitialUserInfoRequestDto.java
src/main/java/com/soda/member/dto/member/LoginResponse.java
src/main/java/com/soda/member/entity/Member.java
src/main/java/com/soda/member/service/AuthService.java
src/main/java/com/soda/member/service/MemberService.java
src/main/java/com/soda/project/controller/ProjectController.java
src/main/java/com/soda/project/domain/ProjectResponse.java
src/main/java/com/soda/project/repository/CompanyProjectRepository.java
src/main/java/com/soda/project/repository/MemberProjectRepository.java
src/main/java/com/soda/project/service/CompanyProjectService.java
src/main/java/com/soda/project/service/MemberProjectService.java
src/main/java/com/soda/project/service/ProjectService.java

개별 프로젝트 조회 API 응답에 **현재 API를 호출한 사용자**의 역할 정보를 추가했습니다. 
이를 통해 클라이언트는 사용자의 프로젝트 내 역할 및 소속 회사의 역할(고객사/개발사)을 바로 확인할 수 있습니다.
1.  **프로젝트 응답 DTO 수정 (`ProjectResponse`):**
*   `currentUserProjectRole` 필드 추가: 조회 중인 사용자의 해당 프로젝트 내 역할 
*   `currentUserCompanyRole`필드 추가: 조회 중인 사용자가 속한 회사의 해당 프로젝트 내 역할 
2.  **역할 조회 서비스 로직 추가:**
*   `MemberProjectService`: `getMemberRoleInProject` 메소드를 추가하여 특정 멤버의 프로젝트 내 역할을 조회합니다.
*   `CompanyProjectService`: `getCompanyRoleInProject` 메소드를 추가하여 특정 회사의 프로젝트 내 역할을 조회합니다.
3.  **프로젝트 조회 로직 수정 (`ProjectService`):**
*   `getProject` 메소드가 현재 사용자 ID와 역할(`userRole`)을 받도록 시그니처를 변경했습니다.
*   `mapToProjectResponse` 메소드에서 현재 사용자 정보를 기반으로 `MemberProjectService`와 `CompanyProjectService`의 역할 조회 메소드를 호출하고, 그 결과를 `ProjectResponse` DTO의 새 필드에 매핑합니다.
4.  **컨트롤러 수정 …

[feature] 프로젝트 조회 응답에 현재 사용자 역할 추가 

---

src/main/java/com/soda/request/repository/RequestRepositoryImpl.java

- 승인요청 조회시 삭제된 데이터도 가져오는 버그 수정 
#131 
- 승인요청 조회하는 API의 QueryDSL 메서드에서 where절에 조건 추가하여 해결하였습니다.
Closed #131

[Fix] 승인요청 조회시 삭제된 데이터도 가져와지는 버그 수정

---

src/main/java/com/soda/global/security/config/SecurityConfig.java
src/main/java/com/soda/request/controller/RequestController.java
src/main/java/com/soda/request/dto/request/ApproverDTO.java
src/main/java/com/soda/request/dto/request/ApproverDeleteResponse.java
src/main/java/com/soda/request/dto/request/MemberAssignDTO.java
src/main/java/com/soda/request/dto/request/RequestCreateRequest.java
src/main/java/com/soda/request/dto/request/RequestCreateResponse.java
src/main/java/com/soda/request/dto/request/RequestDTO.java
src/main/java/com/soda/request/dto/request/RequestUpdateRequest.java
src/main/java/com/soda/request/dto/request/RequestUpdateResponse.java
src/main/java/com/soda/request/entity/ApproverDesignation.java
src/main/java/com/soda/request/entity/DesignateApprover.java
src/main/java/com/soda/request/entity/Request.java
src/main/java/com/soda/request/error/ApproverDesignationErrorCode.java
src/main/java/com/soda/request/error/RequestErrorCode.java
src/main/java/com/soda/request/repository/ApproverDesignationRepository.java
src/main/java/com/soda/request/service/ApproverDesignationService.java
src/main/java/com/soda/request/service/RequestService.java
src/main/java/com/soda/request/service/ResponseService.java

- 승인요청 생성시 승인권자 지정 기능 개발
#141 
- 승인요청 - 멤버 중간테이블 생성
- 승인요청에 대해 여러명의 승인권자를 지정할 수 있어 다대다매핑이 되어 중간테이블을 생성함
- 그 의미를 함축하도록 ApproverDesignation이라고 테이블명을 네이밍함
- 승인요청 생성/수정 시 승인권자를 여러 명 지정할 수 있게 구현하였음
- 승인요청 상세조회시 DTO에 승인권자들도 반환됨
- 승인요청에 대해 승인/거절 생성시 요청한 사람이 승인권자인지 validate함.
- approverDesignation 삭제하는 API도 구현
Closed #141

[Feature] 승인요청 생성시 승인권자 지정 기능 개발

---

src/main/java/com/soda/request/dto/request/RequestDTO.java

- 삭제된 승인권자가 조회되는 버그 해결
#141 
- #141 에서 승인권자를 삭제하였음에도 승인요청 상세조회시 삭제된 승인권자가 조회되는 버그를 해결하였습니다.
- Request 조회 응답 DTO에서 approver를 출력할 때 isDeleted=false 필터링하는 방식으로 해결하였습니다.

[Fix] 삭제된 승인권자가 조회되는 버그 해결

---

src/main/java/com/soda/global/security/config/SecurityConfig.java

- CORS 설정 중 프론트 url에 www를 빠뜨린 오타를 정정하였음
Closed #145

[CICD & FIX] cors에 프론트 url 오타 정정(www를 빠뜨림)

---

src/main/java/com/soda/member/enums/CompanyProjectRole.java
src/main/java/com/soda/project/controller/ProjectController.java
src/main/java/com/soda/project/dto/ProjectCompanyAddRequest.java
src/main/java/com/soda/project/dto/ProjectCompanyAddResponse.java
src/main/java/com/soda/project/dto/ProjectInfoUpdateRequest.java
src/main/java/com/soda/project/dto/ProjectInfoUpdateResponse.java
src/main/java/com/soda/project/dto/ProjectStatusUpdateRequest.java
src/main/java/com/soda/project/dto/ProjectStatusUpdateResponse.java
src/main/java/com/soda/project/dto/ProjectViewResponse.java
src/main/java/com/soda/project/entity/Project.java
src/main/java/com/soda/project/error/ProjectErrorCode.java
src/main/java/com/soda/project/service/CompanyProjectService.java
src/main/java/com/soda/project/service/ProjectService.java

- 프로젝트 개별 조회 API
- 프로젝트 삭제 API
- 프로젝트 상태 변경 API
- 프로젝트 기본 정보 수정 API
- 프로젝트에 새로운 회사/멤버 추가 API
#138 
- 프로젝트에 고객사 또는 개발사를 추가하는 API를 개발하는 과정에서 company role과 member role이 연관되어야 한다는걸 깨달았습니다.
- 그래서 enum 파일을 리팩토링하였습니다.
- CompanyProjectRole 열거형을 사용하면 코드가 더 직관적이고 명확해집니다. 
- 예를 들어, DEV_COMPANY와 CLIENT_COMPANY 역할에 각각 맞는 managerRole과 memberRole을 열거형 내에서 정의함으로써, 다른 코드에서 이를 참조할 때 훨씬 쉽게 이해할 수 있습니다.
- 회사의 역할에 따른 멤버 역할이 자동으로 매핑되고, 이를 기반으로 일관된 로직을 적용할 수 있습니다.
- 기존에는 프로젝트 수정 시 기본 정보 / 개발사&고객사 수정을 한꺼번에 하도록 구현하였습니다.
- 그러나 기획 회의에서 분리하였으면 좋겠다는 의견을 수렴해 우선 기본 정보 수정하는 API로 수정하였습니다.
- 추후 고객사/개발사 선택, 멤버 선택하는 API를 추가할 예정입니다.

[Feature] 프로젝트 CRUD 일부 구현

---

src/main/java/com/soda/member/enums/CompanyProjectRole.java
src/main/java/com/soda/project/controller/ProjectController.java
src/main/java/com/soda/project/dto/ProjectMemberAddRequest.java
src/main/java/com/soda/project/dto/ProjectMemberAddResponse.java
src/main/java/com/soda/project/error/ProjectErrorCode.java
src/main/java/com/soda/project/repository/CompanyProjectRepository.java
src/main/java/com/soda/project/repository/MemberProjectRepository.java
src/main/java/com/soda/project/service/CompanyProjectService.java
src/main/java/com/soda/project/service/MemberProjectService.java
src/main/java/com/soda/project/service/ProjectService.java

프로젝트 참여 회사/멤버 관리 기능 구현
1. 회사 추가 : 회사 추가 시 멤버도 함께 추가
2. 개별 회사 삭제 : 프로젝트 삭제와 다름 / 회사 삭제 시 해당 회사의 멤버들도 함께 삭제
3. 멤버 추가 : 기존에 프로젝트 참여하는 회사의 다른 멤버들 추가
4. 멤버 삭제 : 기존에 프로젝트 참여하는 멤버 1명 삭제
Closed #138 
- 지난 PR 리뷰를 받고, memberProjectRole이 같이 있는 건 책임 분리가 안되는 거 같아 기존의 enum 파일로 다시 구현하였습니다.
- 변경된 코드 로직
```
private MemberProjectRole determineTargetMemberRole(CompanyProjectRole companyRole) {
if (companyRole == CompanyProjectRole.DEV_COMPANY) {
return MemberProjectRole.DEV_PARTICIPANT;
} else if (companyRole == CompanyProjectRole.CLIENT_COMPANY) {
return MemberProjectRole.CLI_PARTICIPANT;
} else {
log.error("멤버 역할을 결정할 수 없는 회사 역할입니다: {}", companyRole);
throw new GeneralException(ProjectErrorCode.COMPANY_PROJECT_NOT_FOUND);
}
}
private MemberProjectRole determineTargetManagerRole(CompanyProjectRole …
```

[Feature] 프로젝트 참여 회사/멤버 관리 기능 구현

---

src/main/java/com/soda/project/dto/ProjectCreateRequest.java
src/main/java/com/soda/project/service/ProjectService.java
src/main/java/com/soda/project/service/StageService.java

프로젝트 생성 시 사용자가 직접 초기 스테이지(단계) 목록을 생성할 수 있는 기능을 추가했습니다.
기존에는 스테이지가 고정된 목록으로 생성되고 나중에 수정을 해야 했지만, 
이제 프로젝트 생성 요청 시 stageNames 필드를 통해 원하는 초기 스테이지 이름 목록으로 스테이지를 생성할 수 있습니다.
1.  ProjectCreateRequest: List<String> stageNames 필드 추가 (사용자가 정의한 초기 스테이지 이름 목록)
2.  ProjectService: createProject 메소드 내에서 stageService.createInitialStages(project, request.getStageNames()) 호출 로직 추가
3.  StageService:
*   createInitialStages 메소드 시그니처 변경 (Long projectId -> Project project, List<String> stageNames)
*   고정된 INITIAL_STAGE_NAMES 사용 로직 제거
*   전달받은 stageNames 목록 기반으로 스테이지 생성 로직 구현
Close #149

[Fix] 프로젝트 생성 시 초기 스테이지 생성 수정

---

src/main/java/com/soda/project/dto/CompanyAssignment.java
src/main/java/com/soda/project/dto/DevCompanyAssignmentRequest.java
src/main/java/com/soda/project/dto/DevCompanyAssignmentResponse.java
src/main/java/com/soda/project/dto/ProjectCreateRequest.java
src/main/java/com/soda/project/dto/ProjectCreateResponse.java
src/main/java/com/soda/project/repository/MemberProjectRepository.java
src/main/java/com/soda/project/service/MemberProjectService.java
src/main/java/com/soda/project/service/ProjectService.java

프로젝트 생성할때 / 개발사 추가할 때,
각 회사를 순회할 때마다 모든 매니저와 모든 일반 멤버가 해당 회사 소속으로 프로젝트에 중복 할당되는 오류 해결
Closed #151 
- 기존 로직에서, 회사를 다중 선택할 시 오류가 생겼었습니다.
- 각 회사를 순회할 때마다 모든 매니저와 모든 일반 멤버가 해당 회사 소속으로 프로젝트에 중복 할당되는 문제였습니다.
- 따라서 응답받는 DTO 형식을 변경하고, 서비스 로직을 수정하였습니다.
- 각 회사별로 해당 회사의 매니저 ID 리스트와 멤버 ID 리스트를 묶어서 전달하기 위해 공통 DTO를 생성하였습니다.
```
@Getter
@Builder
public class CompanyAssignment {
@NotNull(message = "회사 ID는 필수입니다.")
private Long companyId;
// 담당자 목록은 필수
@NotEmpty(message = "담당자 ID 목록은 필수입니다.")
private List<Long> managerIds;
// 일반 참여자 목록은 선택 사항
private List<Long> memberIds;
}
```
- DTO가 변경됨에 따라 request, respons 도 수정하였습니다.
- 또한 서비스 로직도 수정하였습니다.

[Fix] 프로젝트 생성/개발사 추가 시, 회사와 멤버를 중복 추가 시 생기는 오류 해결

---

src/main/java/com/soda/global/config/QueryDslConfig.java
src/main/java/com/soda/project/controller/ProjectController.java
src/main/java/com/soda/project/dto/ProjectMemberSearchCondition.java
src/main/java/com/soda/project/repository/MemberProjectRepository.java
src/main/java/com/soda/project/repository/MemberProjectRepositoryCustom.java
src/main/java/com/soda/project/repository/MemberProjectRepositoryImpl.java
src/main/java/com/soda/project/service/MemberProjectService.java
src/main/java/com/soda/project/service/ProjectService.java

프로젝트에 속한 멤버들 조회 기능 query 부분 리팩토링
Closed #155 
- QueryDSL 쿼리를 작성하고 실행하는 데 필요한 핵심 도구인 JPAQueryFactory 객체를 만들어서 스프링(Spring)이 관리하는 빈(Bean)으로 등록하기 위해서 생성하였습니다.
- 기존 쿼리문이 너무 복잡하고 길어서 안정성이 떨어졌습니다.
- 그래서 코드 리뷰도 받은 겸, 작업 중인 리팩토링을 완료하여 해당 쿼리문을 삭제하였습니다.
- custom repository를 생성하여 복잡한 동적 쿼리를 구현하였습니다.
- 기존 request param을 하나로 모아 `ProjectMemberSearchCondition`라는 새로운 DTO를 만들었습니다.

[Refactor] 프로젝트에 속한 멤버들 조회 기능 query 부분 리팩토링

---

src/main/java/com/soda/project/dto/ProjectMemberSearchCondition.java
src/main/java/com/soda/project/repository/MemberProjectRepositoryCustom.java
src/main/java/com/soda/project/repository/MemberProjectRepositoryImpl.java
src/main/java/com/soda/project/service/MemberProjectService.java
src/main/java/com/soda/project/service/ProjectService.java

- 현재 프로젝트에 속한 멤버 조회할 때 memberId를 기반으로 조회할 수 있게 수정
#159 
- Request를 상세조회할 때 approver의 이름, 프로젝트에서의 Role등을 반환하게 하려했는데 연관관계가 복잡하여 Request를 조회해서 받은 승인권자의 id(memberId)를 바탕으로 GET projects/{projectId}/member?memberId={memberId} 로 보내서 멤버의 이름, 프로젝트에서의 권한을 받는 방식으로 해결하기 위해 GET projects/{projectId}/member API를 수정하였습니다.

[Refactor] 현재 프로젝트에 속한 멤버 조회할 때 memberId를 기반으로 조회할 수 있게 수정

---

src/main/java/com/soda/project/entity/MemberProject.java
src/main/java/com/soda/project/repository/MemberProjectRepository.java
src/main/java/com/soda/project/service/MemberProjectService.java

프로젝트에 회사 추가 시 기존 사용자 권한 수정 안되는 버그 수정
closed #160 
- `MemberProject` entity에 `chageRole` 추가했습니다. (role을 수정하기 위한 메서드)
- 기존 멤버가 존재하는 경우 역할이 다르면 -> 해당 멤버의 권한 바꾸기
- 기존 멤버가 존재하는 경우 역할이 같으면-> 아무것도 변경하지 않음
- 기존 멤버가 없으면 -> 새로운 멤버 추가
- 위와 같은 경우의 수를 생각하도록 로직을 수정하였습니다.

[Fix] 프로젝트에 회사 추가 시 기존 사용자 권한 수정 안되는 버그 수정

---

src/main/java/com/soda/request/dto/response/RequestApproveResponse.java
src/main/java/com/soda/request/dto/response/RequestRejectResponse.java
src/main/java/com/soda/request/dto/response/ResponseDTO.java
src/main/java/com/soda/request/dto/response/ResponseDeleteResponse.java
src/main/java/com/soda/request/dto/response/ResponseUpdateResponse.java
src/main/java/com/soda/request/entity/Request.java
src/main/java/com/soda/request/entity/Response.java
src/main/java/com/soda/request/enums/RequestStatus.java
src/main/java/com/soda/request/enums/ResponseStatus.java
src/main/java/com/soda/request/service/RequestService.java
src/main/java/com/soda/request/service/ResponseService.java

- 승인권자가 여러명일 때 한 명이 승인하거나 거절했을 때 승인요청의 상태가 변경되는 버그 수정
#163 
- 승인권자가 여러명이 가능해지면서 여러명이 전부 승인해야 Request가 approved되는 것으로 처리되는 것이 자연스럽습니다.
- 따라서 기존에 Request에만 승인상태를 저장하던 것을,  RequestStatus에 APPROVING이라는 상태를 추가하고, ResponseStatus를 정의한 뒤 Response에 status(APPROVED, REJECTED)를 추가하였습니다.
- 아래는 Request의 승인 상태 변경 규칙입니다.
- 승인권자들이 아무도 승인/거절 하지 않으면 : 대기중
1명이라도 거절하면 : 거절됨  
1~(n-1)명 승인하면: 승인중  
n명 승인하면: 승인됨
승인요청에 대해 승인권자의 일부가 거절하면 거절됨으로 표시되고, 이에 대해 승인요청한 사람은 "재요청"을 할 수 있게 하려고합니다. 
이때 승인요청하는 사람이 거절한 사람에 대해서만 승인권자를 지정하거나 요청이 수정됐으니 재확인하라는 측면에서 승인했던 사람들도 지정할 수 있습니다. (승인요청자의 책임입니다). 즉 댓글의 대댓글처럼, 게시글의 답글처럼 승인요청에 대해서도 재승인요청을 만들 계획입니다.
Closed #163

[Fix] 승인권자가 여러명일 때 한 명이 승인하거나 거절했을 때 승인요청의 상태가 변경되는 버그 수정

---

src/main/java/com/soda/request/controller/RequestController.java
src/main/java/com/soda/request/dto/request/ReRequestCreateRequest.java
src/main/java/com/soda/request/dto/request/ReRequestCreateResponse.java
src/main/java/com/soda/request/dto/request/RequestCreateRequest.java
src/main/java/com/soda/request/dto/request/RequestDTO.java
src/main/java/com/soda/request/dto/request/RequestDeleteResponse.java
src/main/java/com/soda/request/dto/request/RequestUpdateResponse.java
src/main/java/com/soda/request/entity/Request.java
src/main/java/com/soda/request/error/RequestErrorCode.java
src/main/java/com/soda/request/service/RequestService.java

- 승인요청에 대해 승인권자의 일부가 거절하면 거절됨으로 표시되고, 이에 대해 승인요청한 사람은 "재승인요청"을 할 수 있게 구현하였습니다.
- 이 때 승인요청하는 사람이 거절한 사람에 대해서만 승인권자를 지정하거나 요청이 수정됐으니 재확인하라는 측면에서 승인했던 사람들도 지정할 수 있습니다. (승인요청자의 책임입니다). 즉 댓글의 대댓글처럼, 게시글의 답글처럼 승인요청에 대해서도 재승인요청을 구현하였습니다.
#165 
- 특정 승인요청에 대해 거절되었을 경우 재승인요청을 보낼 수 있는 기능을 구현하였음.
- POST requests/{requestId}/re-requests
- 승인이 거절되었을 경우만 재승인요청을 보낼 수 있으며 이 때 생성되는 승인요청은 일반 승인요청과 똑같이 필드가 들어감(제목, 내용, 링크, 파일, 승인권자)
- 승인권자도 재지정할 수 있음.
- 승인요청자가 거절한 사람만 지정하거나 내용이 변경되었으므로 승인한 사람도 다시 봐야한다고 판단하면 승인권자를 전체로 할 수도 있음. 상황에 따라 유동적이기 때문에 재승인요청에서 승인권자 지정 책임을 승인요청자에게 넘겼음.
- 재승인요청은 기본적으로 승인요청 테이블에 들어가므로 수정/삭제/조회 등은 일반 승인요청에서 하는것 처럼 하면 됨.

[Feature] 재승인요청 기능 개발

---

src/main/java/com/soda/project/service/ProjectService.java

사용자가 참여 중인 프로젝트가 없는 경우 오류가 발생하는 부분을 수정하였습니다.
#190 
- `/projects/my` API를 통해 사용자가 참여 중인 프로젝트 목록 조회 시, 참여 중인 프로젝트가 없는 경우 오류가 발생하였습니다.
- 오류 발생 대신 빈 리스트가 출력되도록 수정하였습니다.
Closed #190

[Fix] 사용자가 참여 중인 프로젝트 목록이 없으면 경우 오류 수정

---

src/main/java/com/soda/global/log/dataLog/aspect/EntityLogAspect.java
src/main/java/com/soda/request/dto/request/ReRequestCreateResponse.java
src/main/java/com/soda/request/dto/request/RequestCreateResponse.java
src/main/java/com/soda/request/dto/request/RequestDTO.java
src/main/java/com/soda/request/dto/request/RequestDeleteResponse.java
src/main/java/com/soda/request/dto/request/RequestUpdateResponse.java

- Request 수정 요청시 로깅에서 500에러 뜨는 버그 해결
#169 
- Request에 ParentId필드가 추가되면서 응답DTO의 fromEntity에서 parentId가 null이면 null을 반환하게 처리하였는데, null일 경우 로깅시 500에러가 발생.
- parentId가 null이면 -1을 반환하게 수정하여 해결하였음.
Closed #169

[Refactor] Request 수정 요청시 로깅에서 500에러 뜨는 버그 해결

---

src/main/java/com/soda/article/controller/ArticleController.java
src/main/java/com/soda/article/dto/article/MyArticleListResponse.java
src/main/java/com/soda/article/error/ArticleErrorCode.java
src/main/java/com/soda/article/repository/ArticleRepository.java
src/main/java/com/soda/article/repository/ArticleRepositoryCustom.java
src/main/java/com/soda/article/repository/ArticleRepositoryImpl.java
src/main/java/com/soda/article/service/ArticleService.java

사용자가 작성한 게시글 목록 조회 기능
#198 
- 기본적으로 사용자가 작성한 게시글 목록 조회 기능을 구현했습니다.
- `@RequestParam(required = false) Long projectId`를 통해 프로젝트 별로 필터링할 수 있습니다.
- 페이지네이션 적용했습니다.
- ArticleRepositoryImpl에 QueryDSL을 사용한 findMyArticlesData 구현
- Article, Stage, Project 조인을 위해 생성
- select() 절을 사용하여 DTO 필드에 필요한 데이터를 Tuple로 조회.
- where() 절에 작성자 ID, 삭제 여부, 동적 projectId 필터링 조건 적용.
- 페이징 및 기본 정렬 적용.
- Tuple에서 데이터를 추출하고 @Builder를 사용하여 DTO 생성
close #198

[Feature] 사용자가 작성한 게시글 목록 조회 기능

---

src/main/java/com/soda/project/controller/ProjectController.java
src/main/java/com/soda/project/dto/MyProjectListResponse.java
src/main/java/com/soda/project/repository/ProjectRepository.java
src/main/java/com/soda/project/repository/ProjectRepositoryCustom.java
src/main/java/com/soda/project/repository/ProjectRepositoryImpl.java
src/main/java/com/soda/project/service/ProjectService.java

로그인한 사용자가 속한 회사가 참여 중인 프로젝트 목록 조회 기능 추가했습니다.
#191 
- 사용자가 프로젝트 목록 조회할 때 해당 사용자의 role, 회사의 role이 필요해서 response를 새로 생성했습니다.
- 사용자가 참여 중인 프로젝트 목록 / 사용자의 회사가 참여 중인 프로젝트 목록 조회할 때 사용합니다.
- getMyProjectsData 메서드에서는 Project, MemberProject, CompanyProject 세 엔티티를 조인해야 해서 복잡한 조인과 조건을 타입 안전하고 명확하게 표현할 수 있게 따로 생성하였습니다.
- Tuple은 QueryDSL에서 여러 타입의 조회 결과를 하나의 묶음으로 반환하기 위한 객체입니다. 
- @QueryProjection을 사용하지 않고 리포지토리에서 다양한 데이터를 조합하여 반환해야 할 때 유용하다고 해서 적용했습니다.
- 리포지토리는 데이터 조회 책임만 지고 서비스에서 최종 DTO 변환을 수행하도록 관심사를 분리할 수 있습니다.
- 서비스에서는 tuple.get(index, Type.class)를 통해 Tuple 내부의 데이터에 접근합니다.
Closed #191

[Feature] 사용자의 회사가 참여 중인 프로젝트 목록 조회 기능

---

src/main/java/com/soda/article/controller/ArticleController.java
src/main/java/com/soda/article/dto/article/VoteViewResponse.java
src/main/java/com/soda/article/service/ArticleService.java

게시글에 투표 존재 시, 투표 정보 조회하는 기능 추가
#173 
- 해당 기능은 투표가 없는 경우  null / 투표가 존재하는 경우 투표의 제목, 항목들을 조회하는 기능입니다.
- 투표 결과를 조회하는 기능은 따로 분리하여 추후 개발 예정입니다.
Closes #173

[Feature] 게시글 투표 기본 정보 조회 기능

---

src/main/java/com/soda/request/controller/RequestController.java
src/main/java/com/soda/request/dto/request/GetMemberRequestCondition.java
src/main/java/com/soda/request/repository/RequestRepositoryCustom.java
src/main/java/com/soda/request/repository/RequestRepositoryImpl.java
src/main/java/com/soda/request/service/RequestService.java

- Request 작성자, 승인권자, 프로젝트(선택)을 바탕으로 조회하는 API 구현
#193 
- 사용자 대시보드의 "최근 요청사항", 내 요청사항 목록에서 사용되는 API입니다.
- GET members/{memberId}/requests?projectId
- Request의 작성자 "or" 승인권자 == memberId인 Request를 페이지네이션하여 조회해옵니다. 
이 때, projectId를 쿼리파라미터로 넣어 필터링 조건으로 사용할 수 있습니다.
- 저희 시스템은 회원가입 시점에 고객사/개발사인지 정해지는 것이 아니라 프로젝트 생성 시점에 정해지기 때문에, 현재 로그인한 일반사용자의 대시보드에서 "내가 최근 요청한 승인요청 목록"/"내가 최근 요청받은 승인요청 목록" 을 둘 다 보여주면 사용자 경험이 좋지 않습니다. (회사의 특성상 일반적으로 한 유저는 개발사로서만, 고객사로서만 활동할 가능성이 크기 때문입니다.) 따라서 "최근 요청사항"이라고 대시보드 요소를 뭉뚱그리고 여기에 "내가 최근 요청한 승인요청 목록"/"내가 최근 요청받은 승인요청 목록"을 함께 보여주는 방식으로 화면 구성하였습니다. 
- Fetch Join
- Request의 승인권자를 조회할 때 ApproveDesignation이라는 엔티티에 접근해야하는데 이 때 n+1문제가 발생할 수 있어, 처음 Request를 QueryDSL로 가져올 때 승인권자지정 테이블을 Fetch JOIN하여 가져오는 방식으로 n+1문제를 예방하였습니다.
- 사실 이 API 이외의 여러 API의 리포지토리 메서드를 보면 n+1이 발생할 수 있는 쿼리들이 …

[Feature] Request 작성자, 승인권자, 프로젝트(선택)을 바탕으로 조회하는 API 구현

---

src/main/java/com/soda/request/dto/GetRequestCondition.java
src/main/java/com/soda/request/repository/RequestRepositoryImpl.java

- 특정 프로젝트의 승인요청 조회 API에 검색조건 추가
#188 
- 기존 특정 프로젝트의 승인요청을 조회하는 API (`GET projects/{projectId}/requests`)에 **검색조건**을 추가하였음.
- 검색 조건
- 승인요청의 **제목**과 **작성자** 기반으로 검색이 가능함.
- 검색 방법
- 두 키워드를 각각 따로 주는 것이 아니라 
`GET projects/{projectId}/requests?keyword=happy `
이런 식으로 요청을 보내면 happy라는 키워드가 제목이나 작성자에 있는지 **OR 조건**으로 검색함.
- 구현 방법
- QueryDSL의 `containsIgnoreCase`을 사용하였음. SQL의 LIKE문 + lower(대소문자 구분x)를 생성시켜주는 메서드임.

[Feature] 특정 프로젝트의 승인요청 조회 API에 검색조건 추가

---

src/main/java/com/soda/global/log/dataLog/aspect/EntityLogAspect.java
src/main/java/com/soda/global/log/dataLog/domain/DataLog.java
src/main/java/com/soda/global/log/dataLog/domain/DataLogCustomRepositoryImpl.java
src/main/java/com/soda/global/log/dataLog/dto/DataLogSearchRequest.java

- 데이터 로그 키워드 검색 기능 구현
#187 
- operatorId, beforeData, afterData의 데이터를 키워드 검색할 수 있게하는 기능을 기존 로그 조회 API(GET /logs)에 추가하였습니다.
- 검색 방법
- GET /logs호출시 쿼리파라미터에 keyword를 함께 요청하면 operatorId, beforeData의 데이터들, afterData의 데이터들과 대조하여 keyword가 있을 시 데이터 반환됩니다.
- 구현 방법
- 기존에는 beforeData, afterData가 json객체(Document)의 형식으로 저장되고 있어 LIKE 검색이 불가능하였음. 따라서 데이터 로깅시 이들의 String버전인 beforeDataText, afterDataText 필드를 추가로 로깅하고 검색시 Text필드에서 검색하는 방식으로 키워드 검색을 구현하였음.
- 몽고DB에는 LIKE검색이 없어 몽고DB Criteria의 regex를 사용하여 키워드검색을 구현하였음.
- 인덱스를 타지 않는다는 단점이 있어 차후 성능을 고려해 몽고db의 text index를 사용한다거나 검색시 Elasticsearch를 사용하는 것을 고려해볼 수 있음.

[Feature] 데이터 로그 키워드 검색 기능 구현

---

src/main/java/com/soda/request/controller/RequestController.java
src/main/java/com/soda/request/repository/RequestRepositoryCustom.java
src/main/java/com/soda/request/repository/RequestRepositoryImpl.java
src/main/java/com/soda/request/service/RequestService.java

- 특정 프로젝트 승인요청 전체 조회시 projectId 조건 추가
#205 
- 기존 특정 프로젝트의 승인요청 전체 조회하는 API에 가장 중요한 projectId 필터링 조건이 없어 projectId 경로 변수에 어떤 값을 전달하든 모든 승인요청이 조회됐었음. 
- 따라서 특정 프로젝트 승인요청 전체 조회시 projectId 조건을 추가하는 방식으로 버그 해결하였음.

[Fix] 특정 프로젝트 승인요청 전체 조회시 projectId 조건 추가

---

src/main/resources/application.yml

- 1MB 이상의 파일도 저장할 수 있게 수정
- #176 
- spring servlet multipart의 max-file-size, max-request-size를 5MB로 설정하여 최대 용량을 늘림
- 더 늘릴 수 있는데 S3의 무료 용량 제한이 5GB여서 소극적으로 5MB로 늘렸습니다. (기본 설정 1MB)

[Refactor] 1MB 이상의 파일도 저장할 수 있게 수정

---

src/main/java/com/soda/article/controller/ArticleController.java
src/main/java/com/soda/article/dto/article/VoteSubmitRequest.java
src/main/java/com/soda/article/dto/article/VoteSubmitResponse.java
src/main/java/com/soda/article/error/VoteErrorCode.java
src/main/java/com/soda/article/repository/ArticleRepositoryCustom.java
src/main/java/com/soda/article/repository/ArticleRepositoryImpl.java
src/main/java/com/soda/article/repository/VoteAnswerItemRepository.java
src/main/java/com/soda/article/repository/VoteAnswerRepository.java
src/main/java/com/soda/article/repository/VoteRepository.java
src/main/java/com/soda/article/service/ArticleService.java
src/main/java/com/soda/article/service/VoteAnswerItemService.java
src/main/java/com/soda/article/service/VoteAnswerService.java
src/main/java/com/soda/article/service/VoteItemService.java
src/main/java/com/soda/article/service/VoteService.java
src/main/java/com/soda/member/repository/MemberRepository.java
src/main/java/com/soda/member/service/MemberService.java

투표하기 기능
#170 
- 중복 투표 불가능
- ADMIN이 작성한 경우 : 고객사/개발사 전부 투표 가능
- 고객사 직원이 작성한 경우 : 개발사만 투표 가능
- 개발사 직원이 작성한 경우 : 고객사만 투표 가능
- 기존에는 `findByIdAndIsDeletedFalse` 메서드로 게시글 유효성 검사를 했었습니다.
- 그러나 게시글 조회 시 연관된 Member와 Company 정보를 함께 효율적으로 가져오기 위해`findByIdAndIsDeletedFalseWithMemberAndCompanyUsingQuerydsl` 메서드를 추가하여 적용했습니다.
- 다중선택 : 리스트 형식으로 여러 항목을 선택할 수 있습니다.
- 단일선택: 리스트 size 1로 제한하여 하나만 선택할 수 있습니다.
- 텍스트 입력 : 텍스트 입력을 할 수 있습니다.
- 멤버 조회 시 연관된 Company 정보를 효율적으로 가져오기 위해 쿼리문을 작성했습니다.
- 추후 querydsl로 리팩토링하면 좋을 듯 합니다.
close #170

[Feature] 투표하기 기능 추가

---

src/main/java/com/soda/article/controller/ArticleController.java
src/main/java/com/soda/article/dto/article/VoteResultResponse.java
src/main/java/com/soda/article/repository/VoteAnswerItemRepository.java
src/main/java/com/soda/article/repository/VoteAnswerItemRepositoryCustom.java
src/main/java/com/soda/article/repository/VoteAnswerItemRepositoryImpl.java
src/main/java/com/soda/article/repository/VoteAnswerRepository.java
src/main/java/com/soda/article/service/ArticleService.java
src/main/java/com/soda/article/service/VoteAnswerItemService.java
src/main/java/com/soda/article/service/VoteAnswerService.java
src/main/java/com/soda/article/service/VoteService.java

사용자는 투표 ID를 통해 해당 투표의 총 참여자 수, 항목별 득표 수 및 비율(항목 선택형 투표의 경우), 또는 제출된 텍스트 답변 목록(텍스트 답변형 투표의 경우)을 확인할 수 있습니다.
#201 
- 투표율을 계산하기 위해 추가했는데, 만약 필요가 없다고 판단되면 삭제해도 됩니다.
- 항목별 득표 수를 효율적으로 집계하기 위해 QueryDSL을 사용한 Custom Repository 로직을 구현했습니다.
- countItemGroupByVoteItemId(Long voteId): 특정 투표 ID에 대해 VoteAnswerItem을 voteItem.id 기준으로 그룹화하고 개수를 세어 Map<Long, Long> 형태로 반환합니다.
- `VoteAnswerService`
- `countAnswers`: 특정 투표(Vote)에 대한 총 답변 수를 조회하는 메서드
- `findTextAnswers`: 특정 투표(Vote)에 대한 모든 텍스트 답변 목록을 조회하는 메서드
- `VoteAnswerItemService`
- `countItemsByVote`: 특정 투표 ID에 대해 각 투표 항목(VoteItem)별 득표 수를 집계하는 메서드
```{
"status": "success",
"code": "200",
"message": "OK",
"data": {
"voteId": 2,
"title": "점심 메뉴 선택 (하나만!)",
"allowMultipleSelection": false,
"allowTextAnswer": false,
"deadLine": null,
"totalParticipants": 2, …
```

[Feature] 게시글 투표 결과 조회 기능

---

src/main/java/com/soda/project/controller/ProjectController.java
src/main/java/com/soda/project/dto/ProjectSearchCondition.java
src/main/java/com/soda/project/repository/ProjectRepositoryCustom.java
src/main/java/com/soda/project/repository/ProjectRepositoryImpl.java
src/main/java/com/soda/project/service/ProjectService.java

기존에 있던 프로젝트 목록 전체 조회 API에 검색 기능 추가했습니다.
사용자의 프로젝트 목록 조회 API에 검색 기능 / 상태 별 필터링 기능 추가했습니다
#184 
- `@ModelAttribute`로 한번에 파일로 받아서 검색 또는 필터링 하기 위해 새로 생성하였습니다.
- status 별로 조회하거나, keyword로 검색하도록 하였습니다.
- status를 추가하는 경우 필터링해서 조회하는 기능을 추가했습니다.
- 그 외에 keyword를 추가하여 프로젝트 제목으로 검색하는 기능을 추가했습니다.
Close #184

[Feature] 프로젝트 제목으로 검색 기능 추가

---

src/main/java/com/soda/request/dto/request/RequestDTO.java

- 멤버id 기반 승인요청 조회시 projectId도 반환되도록 수정
#216 
- 승인요청 페이지네이션 조회 API의 RequestDTO에 projectId 필드를 추가하는 방식으로 구현하였습니다

[Feat] 멤버id 기반 승인요청 조회시 projectId도 반환되도록 수정

---

src/main/java/com/soda/request/dto/request/GetMemberRequestCondition.java
src/main/java/com/soda/request/repository/RequestRepositoryImpl.java

- 특정 멤버 승인요청 조회 API 에서 키워드 기반 검색 기능 구현
#218 
- 이전에 구현한 키워드 검색 기능들처럼, 검색조건DTO에 keyword필드 추가하고, 검색에 해당하는 QueryDSL메소드에 keyword 필터링 조건을 추가하여 구현하였습니다.

[Feature] 특정 멤버 승인요청 조회 API 에서 키워드 기반 검색 기능 구현

---

src/main/java/com/soda/notice/controller/NoticeController.java
src/main/resources/application.yml

실시간 알림 수신을 위한 SSE 구독 엔드포인트(`GET /notices/subscribe`)를 구현했습니다.
-   클라이언트 연결 시 `SseEmitter`를 생성하여 `text/event-stream` 형식으로 응답합니다.
-   기본 타임아웃은 1시간으로 설정됩니다.
-   초기 연결 확인을 위한 더미 이벤트(`name: connect`)를 전송합니다.
-   **🚨 중요:** 현재는 연결 수립 기능만 구현되었으며, Emitter 저장/관리 및 실제 알림 전송 로직은 포함되지 않습니다 (후속 구현 예정).
-   **보안:** 테스트를 위해 임시로 `/notices/**` 경로의 JWT 인증을 비활성화했습니다. **추후 수정 필요합니다.**
Close #178

[Feature] SSE 구독 엔드포인트 구현

---

src/main/java/com/soda/project/error/ProjectErrorCode.java
src/main/java/com/soda/project/repository/CompanyProjectRepository.java
src/main/java/com/soda/project/service/CompanyProjectService.java
src/main/java/com/soda/project/service/MemberProjectService.java

고객사/개발사 멤버 제대로 추가 안되는 버그 수정
#228 
- 프로젝트에 새로운 회사/멤버 추가하는 API 테스트 시, DB에 제대로 저장이 되지 않는데 200 OK가 되는 오류가 발생했습니다.
- 기존에는 DB에 이미 존재하는지 여부를 확인하고 삭제된 회사/멤버를 재할당하거나 role을 변경해주는 조건이 있었는데 삭제했습니다.
- 프로젝트에 회사/멤버를 새로 할당하고 저장되도록 조건들을 삭제해주었습니다.

[Fix] 고객사/개발사 멤버 제대로 추가 안되는 버그 수정

---

src/main/java/com/soda/project/service/ProjectService.java

프로젝트 상태 진행중으로 변경 로직 추가
#231 
- 개발사 지정 시, [계약중] 상태에서 [진행중] 상태로 변경되는 로직을 추가하였습니다.
- `/projects/{projectId}/dev-companies` 는 처음에 개발사가 없는 프로젝트에 개발사를 추가할 때만 사용되는 API입니다.
- 따라서 개발사 지정 시 해당 프로젝트가 [진행중] 이라고 생각하여 자동으로 상태를 변경하도록 했습니다.
- 그 이후에는 각 프로젝트의 담당자들 또는 관리자가 직접 프로젝트 상태 관리를 할 수 있습니다.
Closed #231

[Feature] 프로젝트 상태 진행중으로 변경 로직 추가

---

src/main/java/com/soda/notice/service/EmitterService.java

실시간 사용자 알림 기능 구현의 일환으로 Server-Sent Events (SSE) 기술을 선택했습니다.
SSE는 서버에서 클라이언트로의 단방향 데이터 푸시에 효율적이며,
웹소켓에 비해 구현이 비교적 간단하다는 장점이 있어 실시간 알림에 적합하다고 판단했습니다.
실시간 알림을 위한 SSE(Server-Sent Events) 연결을 관리하는 `EmitterService`를 구현합니다.
-   **EmitterService 구현:**
-   사용자 ID를 키로 `SseEmitter` 객체를 `ConcurrentHashMap`에 저장 및 관리합니다.
-   주요 기능: Emitter 추가, 제거, 조회 기능
-   **목적:** 향후 알림 발생 시, 이 서비스를 통해 특정 사용자의 Emitter를 찾아 실시간 알림을 전송합니다.
-   **참고:** 본 PR은 서비스 구현만 포함하며, 실제 사용 로직은 후속 작업(#179 이후)에서 진행됩니다.
Close #179

[Feature] SseEmitter 관리 서비스 구현

---

src/main/java/com/soda/global/security/config/SecurityConfig.java
src/main/java/com/soda/notice/controller/NoticeController.java
src/main/java/com/soda/notice/service/EmitterService.java
src/main/java/com/soda/notice/service/NoticeService.java
src/main/resources/application.yml

SSE 구독 기능의 안정성과 구조를 개선합니다.
-   **인증 적용:** `/notices/subscribe` 엔드포인트에 JWT 인증을 적용하고 `@AuthenticationPrincipal`을 사용합니다.
-   **서비스 분리:** `NoticeService`를 도입하여 Controller의 구독 로직을 분리했습니다.
-   **Emitter 자동 정리:** `EmitterService`에서 연결 종료/타임아웃/오류 시 자동으로 Emitter를 제거하도록 개선했습니다.
-   **알림 전송 기능 추가:** `EmitterService`에 특정 사용자 대상 알림 전송 메서드를 추가했습니다.
Close #181

[Feature] SSE Emitter 관리 및 구독 로직 개선

---

logstash/logstash.conf

- logstash.conf 환경변수 변경
#174 
- 젠킨스 서버에서 logstash.conf 파일의 몽고db URI가 읽히지 않는 버그를 수정하였습니다.
- 기존에 .env의 환경변수 + 문자열로 읽히게 하던 것을 깔끔하게 환경변수에 문자열까지 함께 저장하고 conf파일에서 환경변수만 읽도록 수정하였습니다.

[Fix] logstash.conf 환경변수 변경

---

logstash/logstash.conf

- logstash.conf 환경변수에 쌍따옴표("") 추가
#174 
- logstash.conf에서 실수로 쌍따옴표("")를 빠뜨려 추가합니다.
- logstash.conf에서는 환경변수를 쌍따옴표("")로 감싸야 환경변수로 인식합니다.

[Fix] logstash.conf 환경변수에 쌍따옴표("") 추가

---

src/main/java/com/soda/notice/controller/NoticeController.java
src/main/java/com/soda/notice/service/EmitterService.java

SSE 기반 실시간 알림 기능의 개발 및 테스트를 용이하게 하기 위해, 특정 사용자에게 수동으로 테스트 알림을 전송할 수 있는 엔드포인트를 추가합니다.
-   **테스트 엔드포인트 구현:**
-   `POST /notices/send-test/{userId}` 경로를 추가했습니다.
-   이 엔드포인트는 Request Body로 받은 메시지(`{"message": "..."}`)를 지정된 `userId`를 구독 중인 클라이언트에게 `test_notification` 이벤트로 전송합니다.
-   `NoticeService`의 `sendNotification` 메서드를 사용하여 실제 SSE 이벤트를 발생시킵니다.
-   **타임아웃 조정:**
-   `EmitterService`의 `DEFAULT_TIMEOUT` 값을 다시 1시간으로 조정했습니다 (이전 임시 변경값 복구).
-   **목적:** 프론트엔드 개발 또는 백엔드 알림 로직 테스트 시, 실제 이벤트 발생을 기다리지 않고 SSE 연결 및 메시지 수신을 간편하게 확인할 수 있도록 지원합니다.
Close #182

[Feature] SSE 테스트 알림 전송 엔드포인트 추가

---

src/main/java/com/soda/article/dto/article/ArticleViewResponse.java

게시글 조회 시 게시글 상태 조회 안되는 오류 수정
#245 
- 게시글 하나 조회 시 게시글 상태 조회가 없어서 status를 추가해주었습니다.
- 답변완료/답변대기 상태 변경 API 연동 시 필요하기 때문에 추가했습니다.

[Fix] 게시글 조회 시 게시글 상태 조회 안되는 오류 수정

---

logstash/logstash.conf
src/main/resources/logback-spring.xml

- 저장시각이 문자열로 저장되는 버그 해결, 필요없는 필드 삭제, INFO레벨 이상만 로깅되게 수정
#248 
- 기존에 문자열로 저장되던 로깅시각을 ISO시간형식으로 저장되게 하였음. 현재 시간역순으로 정렬이 잘되고, 차후 검색 등이 요구되면 인덱싱 전략 적용 가능함. 
- "@version", "path", "host", "thread" 등의 필요없는 필드를 삭제하였음.
- 콘솔에는 모든 레벨의 로그가, 파일에 던질때는 INFO레벨 이상만 로깅되게하여 몽고DB에는 INFO레벨 이상의 로그만 저장되게 하였고, 몽고DB에 error_log라는 별도의 컬렉션을 만들어 ERROR레벨의 로그는 error_log에 따로 저장되게 만듦.
- 변경 전
- 변경 후
몽고DB Compass에서 timestamp 기준으로 최신순 정렬이 잘 되는 모습.

[Fix&Refact] 저장시각이 문자열로 저장되는 버그 해결, 필요없는 필드 삭제, INFO레벨 이상만 로깅되게 수정

---

logstash/logstash.conf

- 몽고DB에 중복로깅되는 버그 해결
#250 
- logstash의 이전에 읽은 파일 정보 기억하게 (sicedb_path) 설정하여 해결

[Fix] 몽고DB에 중복로깅되는 버그 해결

---

logstash/logstash.conf

- 로그 생성시간/로깅시간 구분하여 로깅
#252 
- 로그가 생성된 시간과 실제로 몽고DB에 로깅되는 시간을 구분하여 필드에 기록함으로써 중복로깅이나 로깅지연과 같은 문제를 감지하기 용이하게 만듦.
- 로그가 생성된 시간은 created_time, 로깅된 시간은 logging_time 필드에 저장됨.

[Feature] 로그 생성시간/로깅시간 구분하여 로깅

---

src/main/java/com/soda/member/controller/CompanyController.java
src/main/java/com/soda/member/dto/CompanyCreationStatRaw.java
src/main/java/com/soda/member/dto/CompanyCreationTrend.java
src/main/java/com/soda/member/dto/company/CompanyTrendSearchCondition.java
src/main/java/com/soda/member/enums/StatisticsUnit.java
src/main/java/com/soda/member/repository/CompanyRepository.java
src/main/java/com/soda/member/repository/CompanyRepositoryCustom.java
src/main/java/com/soda/member/repository/CompanyRepositoryImpl.java
src/main/java/com/soda/member/service/CompanyService.java

관리자가 지정된 기간 및 단위(일/주/월)에 따라 회사 생성 추이를 조회하는 API를 구현했습니다. 
관리자 대시보드에서 사용될 기능입니다.
1.  **API 엔드포인트 추가:** GET /companies/company-creation-trend
2.  **StatisticsUnit Enum 생성:** 일/주/월 단위별 기간 계산 및 포맷팅 로직 캡슐화
3.  **QueryDSL Repository 구현:** CompanyRepositoryCustom 및 구현체 추가, 생성일 기준 Raw 데이터 조회 
4.  **서비스 로직 구현 (`CompanyService`):**
*   Raw 데이터 기반 요청 단위별 집계
*   데이터 없는 기간 0으로 채우는 Zero-Filling 로직 구현
5.  **관련 DTO 추가:** `CompanyTrendSearchCondition`, `CompanyCreationStatRaw`, `CompanyCreationTrend`
*   **현재 방식:** 실시간 DB 조회 및 집계 (관리자 기능이라 낮은 빈도로 요청될 것 같아 실시간 DB조회로 구현)
*   **성능 이슈 발생 시:** 배치 작업으로 통계 테이블 사전 계산 방식 도입 하겠습니다.
Close #239

[Feature] 회사 생성 추이 통계 조회 기능 구현

---

src/main/java/com/soda/project/service/ProjectService.java

만약 조회하려는 기간에 프로젝트를 생성하지 않으면 통계 테이블에 해당 날짜가 저장되지 않아 조회되지 않는 오류를 해결하였습니다.
#259 
- 조회하려는 기간 중 통계 테이블에 존재하지 않는 날짜인 경우 `count 0`으로 조회하도록 추가하였습니다.
- 요청된 timeUnit에 따라 startDate부터 endDate까지 모든 기간(일/주/월)을 반복합니다.
- DAY
- while 루프와 plusDays(1)을 사용하여 명시적으로 반복합니다
- 각 날짜를 yyyy-MM-dd 형식의 dateKey로 만듭니다.
- WEEK
- 시작일과 종료일이 속한 주의 시작일(월요일 기준, WeekFields 사용)을 계산하고, while 루프와 plusWeeks(1)로 반복합니다. 
- 각 주의 시작일에 대해 Repository에서 사용한 주차 형식과 동일한 dateKey 를 생성합니다
- "2025년 4월 둘째주" 이런 식으로 날짜를 조회하기 위해 따로 조회용 날짜 문자열을 생성하였습니다.
- MONTH
- YearMonth와 while 루프, plusMonths(1)을 사용하여 반복합니다. 
- 각 월을 yyyy-MM 형식의 dateKey로 만듭니다.
1. DB 부하 감소
- 데이터베이스는 실제 데이터가 있는 행만 조회하고 집계(GROUP BY, SUM)하면 됩니다.
- 0건인 날짜를 DB에서 억지로 만들어내거나 조인할 필요가 없습니다
- 이는 DB 쿼리를 훨씬 단순하고 빠르게 만듭니다.
2. 유지보수: 통계 표시 방식(0 포함 여부 등) 변경 시 서비스 로직만 수정하면 됩니다.
이런 식으로 서비스 로직에서 데이터가 …

[Fix] 프로젝트 생성을 하지 않는 경우 통계에 저장되지 않는 오류 해결

---

src/main/java/com/soda/article/dto/article/ArticleSearchCondition.java
src/main/java/com/soda/article/repository/ArticleRepositoryImpl.java

게시글 목록 조회 시
우선순위 / 게시글 상태 별로 필터링해서 조회하는 기능을 추가했습니다.
#265 
- `ArticleSearchCondition`에 PriorityType, ArticleStatus 추가
- `searchArticles` 메서드에 해당 필터링 조건 추가

[Feature] 게시글 목록 조회 시 PriorityType, ArticleStatus 필터링 기능 추가

---

src/main/java/com/soda/request/repository/RequestRepositoryImpl.java

- 특정 멤버의 승인요청 조회할 때 승인요청이 속한 project의 isDeleted가 false인 데이터만 조회되게 수정
#267 
- FE에서 내 승인요청 목록에서 삭제된 프로젝트의 승인요청이 출력되는 버그가 발견됨.
- 특정 멤버의 승인요청 조회할 때 승인요청이 속한 project의 isDeleted가 false인 데이터만 조회되게 수정하여 해결함

[Fix] 특정 멤버의 승인요청 조회할 때 승인요청이 속한 project의 isDeleted가 false인 데이터만 조회되게 수정

---

src/main/java/com/soda/global/log/responsetime/ControllerLoggingAspect.java

- 응답시간 로깅시 중괄호를 하나 더 넣어 응답시간이 부정확한 위치에 로깅되는 버그 해결
#270

[Fix] 응답시간 로깅시 중괄호를 하나 더 넣어 응답시간이 부정확한 위치에 로깅되는 버그 해결

---

src/main/java/com/soda/notification/controller/NotificationController.java
src/main/java/com/soda/notification/listener/CommentNotificationListener.java
src/main/java/com/soda/notification/repository/MemberNotificationRepository.java
src/main/java/com/soda/notification/service/MemberNotificationService.java
src/main/java/com/soda/notification/service/NotificationService.java

이 PR은 알림 읽음 기능 구현를 포함하는 **PR #276** 의 변경 사항을 기반으로 합니다. 따라서 **PR #276가 먼저 `develop` 브랜치에 병합되어야 합니다.**
사용자의 모든 읽지 않은 알림을 한 번에 읽음 처리하는 API를 구현했습니다.
-   **전체 읽음 API 추가:** `POST /notifications/read-all` 구현.
-   **서비스 로직:** 사용자의 읽지 않은 모든 알림 조회 후, 각 알림을 반복하며 논리적 삭제(`isDeleted=true`) 처리.
-   **링크 수정:** 댓글 알림 링크를 관련 게시글 경로로 변경.
-   **향후 개선:** 현재는 개별 업데이트 방식이나, 추후 알림 양 증가 시 성능 개선을 위해 **QueryDSL을 이용한 벌크 업데이트** 적용 예정.
Close #224
-   [ ] 최종 결과물을 확인했는가?
-   [ ] 의미 있는 커밋 메시지를 작성했는가?

[Feature] 알림 전체 읽음 기능 구현

---

src/main/java/com/soda/notification/controller/NotificationController.java
src/main/java/com/soda/notification/error/NotificationErrorCode.java
src/main/java/com/soda/notification/listener/CommentNotificationListener.java
src/main/java/com/soda/notification/repository/MemberNotificationRepository.java
src/main/java/com/soda/notification/service/MemberNotificationService.java
src/main/java/com/soda/notification/service/NotificationService.java

이 PR은 알림 목록 조회 기능 및 관련 엔티티/서비스 구조를 포함하는 **PR #275** 의 변경 사항을 기반으로 합니다. 따라서 **PR #275가 먼저 `develop` 브랜치에 병합되어야 합니다.**
사용자 알림을 읽음 처리하는 API를 구현했습니다.
알림 읽음은 해당 `MemberNotification` 레코드의 논리적 삭제(`isDeleted = true`)로 처리합니다.
-   **읽음 API 구현:** `PATCH /notifications/{memberNotificationId}/read` 추가.
Close #223
-   [ ] 최종 결과물을 확인했는가?
-   [ ] 의미 있는 커밋 메시지를 작성했는가?

[Feature]알림 읽음 기능 구현

---

src/main/java/com/soda/notification/controller/NotificationController.java
src/main/java/com/soda/notification/dto/NotificationResponse.java
src/main/java/com/soda/notification/entity/MemberNotification.java
src/main/java/com/soda/notification/error/NotificationErrorCode.java
src/main/java/com/soda/notification/listener/CommentNotificationListener.java
src/main/java/com/soda/notification/repository/MemberNotificationRepository.java
src/main/java/com/soda/notification/service/MemberNotificationService.java
src/main/java/com/soda/notification/service/NotificationService.java

사용자 알림 목록을 페이징하여 조회하는 API(`GET /notices`)를 구현합니다.
**PR #274 ([Feature] 댓글/대댓글 생성 시 실시간 알림 기능 구현)**가 먼저 병합되어야 합니다.
-   **API 구현:** `GET /notices` 엔드포인트 추가
-   **성능 최적화:** `@EntityGraph` 사용하여 N+1 문제 방지.
-   **읽음 처리 변경:** `MemberNotification`의 `isRead` 필드 제거
-  **알림 읽음은 해당 `MemberNotification`의 논리적 삭제(`isDeleted=true`)**로 처리할 예정 (삭제=읽음).
-   DTO(`NotificationResponse`), Service, Repository 관련 로직 구현.
-   효율적인 사용자 알림 목록 조회 기능 제공.
-   읽음 상태 관리 방식 단순화.
Close #222
-   [ ] 최종 결과물을 확인했는가?
-   [ ] 의미 있는 커밋 메시지를 작성했는가?

[Feature] 사용자 알림 목록 조회 API 구현

---

src/main/java/com/soda/member/service/MemberService.java
src/main/java/com/soda/project/application/stage/request/response/ResponseFacade.java
src/main/java/com/soda/project/application/stage/request/validator/RequestApproverValidator.java
src/main/java/com/soda/project/application/validator/ProjectValidator.java
src/main/java/com/soda/project/domain/stage/request/Request.java
src/main/java/com/soda/project/domain/stage/request/RequestService.java
src/main/java/com/soda/project/domain/stage/request/response/Response.java
src/main/java/com/soda/project/domain/stage/request/response/ResponseFactory.java
src/main/java/com/soda/project/domain/stage/request/response/ResponseService.java
src/main/java/com/soda/project/interfaces/ResponseController.java

- Response(Approve) 생성 과정 레이어별로 책임 분리
#280 
- 특정 승인요청에 대해 Approve하는 과정 즉, Approve상태의 Response를 생성하는 과정을 적절히 책임분리 해보았습니다.
- 기존 Service 메서드에서 Validation, 생성, 상태변경 모두를 담당했다면
변경 후에는 Application Layer에서 Validation을 담당하고, Domain Layer의 Service 메서드에서는 흐름만 제어하고, 엔티티에 생성, 상태변경을 위임했습니다. 
- 이 때 Response를 생성할 때 ResponseLink도 생성해야하는데, 기존에 LinkService에서 전략패턴으로 ResponseLink를 생성하도록 구현했었는데 이를 활용하기 위해 ResponseFactory를 정의하고 여기서 Response와 ResponseLink의 생성을 담당하게 하였습니다. (Factory안에서 Response엔티티와 LinkService에 각각 생성 메세지를 보냄)
- 기존에 구현했던 LinkService 전략패턴은 결국 Link의 생성을 Service에서 담당한다는 점에서 DDD의 원칙에 위배되는 것 같아 차후 리팩토링을 고려해보는 것도 좋을 것 같습니다.

[Refact] Response(Approve) 생성 과정 레이어별로 책임 분리

---

src/main/java/com/soda/project/infrastructure/ResponseProviderImpl.java

- 승인요청에 대한 응답이 조회되지 않는 버그를 햐결하였음.
#291 
- ProviderImpl에 Repository 빈을 주입하여 해결하였습니다. (final을 빼먹었었어서 오류가 발생했었음)

[Fix] ProviderImpl에 Repository 빈 주입(final을 빼먹었었음)

---

src/main/java/com/soda/project/application/ProjectFacade.java

- 로깅 엔티티액션 UPDATE_STATUS인 메서드 UPDATE로 변경
#314 
- 로깅을 하는 목적이 관리자가 데이터 변경이력을 확인하기 위함이므로 PATCH와 UPDATE를 구분할 필요는 없음
- 따라서 따로 처리가 안돼있는 UPDATE_STATUS를 고수하고 처리로직을 추가하기보다는 애초에 UPDATE로 액션이 저장되어 로깅되게 수정하였음

[Fix] 로깅 엔티티액션 UPDATE_STATUS인 메서드 UPDATE로 변경

---

src/main/java/com/soda/project/application/stage/request/RequestFacade.java
src/main/java/com/soda/project/application/stage/request/RequestValidator.java
src/main/java/com/soda/project/application/stage/request/response/ResponseFacade.java
src/main/java/com/soda/project/application/validator/ProjectValidator.java

- 개발사 및 어드민이 승인요청 생성/수정/삭제 되지않는 버그 해결
#324 
- 리팩토링 중 승인요청 생성의 권한처리를 고객사쪽으로 잘못 매칭하여 버그 발생하였음. 개발사 및 어드민이 승인요청 생성/수정 가능하게끔 권한처리 로직 추가하였음

[Fix] 개발사 및 어드민이 승인요청 생성/수정/삭제 되지않는 버그 해결

---

src/main/java/com/soda/project/domain/stage/common/file/FileFactory.java

- 파일 메타정보 DB에 저장 할 때 uploads/{uuid}_는 저장되지 않게 수정
#330

[Fix] 파일 메타정보 DB에 저장 할 때 uploads/{uuid}_는 저장되지 않게 수정

---

src/main/java/com/soda/member/application/CompanyFacade.java
src/main/java/com/soda/member/application/MemberFacade.java
src/main/java/com/soda/member/domain/AuthService.java
src/main/java/com/soda/member/domain/company/CompanyProvider.java
src/main/java/com/soda/member/domain/company/CompanyService.java
src/main/java/com/soda/member/domain/member/MemberProvider.java
src/main/java/com/soda/member/domain/member/MemberService.java
src/main/java/com/soda/member/infrastructure/company/CompanyProviderImpl.java
src/main/java/com/soda/member/infrastructure/company/CompanyRepository.java
src/main/java/com/soda/member/infrastructure/company/CompanyRepositoryCustom.java
src/main/java/com/soda/member/infrastructure/company/CompanyRepositoryImpl.java
src/main/java/com/soda/member/infrastructure/member/MemberProviderImpl.java
src/main/java/com/soda/member/infrastructure/member/MemberRepository.java
src/main/java/com/soda/member/infrastructure/member/MemberRepositoryCustom.java
src/main/java/com/soda/member/infrastructure/member/MemberRepositoryImpl.java
src/main/java/com/soda/member/interfaces/AuthController.java
src/main/java/com/soda/member/interfaces/CompanyController.java
src/main/java/com/soda/member/interfaces/dto/company/CompanyResponse.java
src/main/java/com/soda/member/interfaces/dto/company/CompanyUpdateRequest.java
src/main/java/com/soda/member/interfaces/dto/company/CompanyViewOption.java
src/main/java/com/soda/member/interfaces/dto/company/MemberResponse.java
src/main/java/com/soda/member/interfaces/dto/company/MemberViewOption.java
src/main/resources/application.yml

회사(Company) 도메인의 생성, 조회, 수정, 삭제 관련 오류를 수정하고 기능을 개선했습니다.
**주요 변경 사항:**
1.  **수정 오류 해결**:
*   회사 정보 수정 시, 요청 DTO(`CompanyUpdateRequest`)의 특정 필드가 `null`일 경우 업데이트 과정에서 오류가 발생하던 문제를 해결했습니다. 응답 DTO(`CompanyResponse`, `MemberResponse`)에 `@JsonInclude(JsonInclude.Include.NON_NULL)`을 적용하여 `null` 값 필드는 JSON 응답에서 제외되도록 처리하고, 관련 로직에서 NPE 발생 가능성을 줄였습니다.
2.  **DTO 필드 및 유효성 조정**:
*   `MemberResponse`에 `email`, `CompanyName`, `isDeleted` 필드 추가.
*   `CompanyUpdateRequest`의 일부 필드 제약 조건(길이, 패턴)을 현실적인 데이터에 맞게 수정.
3.  **회사 조회 옵션 추가**:
*   `CompanyViewOption` (활성/전체/삭제된 회사)을 도입하여, 조건에 따라 회사 목록을 조회할 수 있도록 기능을 확장했습니다. (`CompanyController`, `Facade`, `Service`, `Provider`, `Repository` 전반에 반영)
4.  **응답 데이터 명확화**:
*   `CompanyResponse`에 `isDeleted` 필드를 추가하여 삭제 여부를 명시적으로 제공.
*   Close #318

[Bug] 회사 관련 생성,조회,수정,삭제 오류 관련 수정

---

src/main/resources/application.yml

SSE(Server-Sent Events) 연결 시, SseEmitter에 설정된 타임아웃(1시간)보다 Spring MVC의 기본 비동기 요청 타임아웃(약 30초)이 먼저 발생하여 SSE 연결이 조기에 종료되는 문제를 해결합니다.
application.yml에 spring.mvc.async.request-timeout=-1 설정을 추가하여 
Spring MVC의 비동기 타임아웃을 비활성화함으로써, SseEmitter가 자체 타임아웃 설정에 따라 동작하도록 수정했습니다.
#335

[Bug] Spring MVC 비동기 타임아웃 적용
