- Dockerfile
젠킨스 CICD 구축을 위해 도커파일 추가하였습니다
[CI/CD] 백엔드 CICD 구축 #2
> [ci/cd] 도커파일 생성

- src/main/java/com/soda/common/BaseEntity.java
- src/main/java/com/soda/global/response/ErrorCode.java
- src/main/java/com/soda/member/repository/CompanyRepository.java
- src/main/java/com/soda/member/repository/MemberRepository.java
- src/main/java/com/soda/project/controller/ProjectController.java
- src/main/java/com/soda/project/domain/CompanyProjectDTO.java
- src/main/java/com/soda/project/domain/MemberProjectDTO.java
- src/main/java/com/soda/project/domain/ProjectCreateRequest.java
- src/main/java/com/soda/project/domain/ProjectCreateResponse.java
- src/main/java/com/soda/project/domain/ProjectDTO.java
- src/main/java/com/soda/project/domain/ProjectListResponse.java
- src/main/java/com/soda/project/domain/ProjectResponse.java
- src/main/java/com/soda/project/entity/CompanyProject.java
- src/main/java/com/soda/project/entity/MemberProject.java
- src/main/java/com/soda/project/entity/Project.java
- src/main/java/com/soda/project/repository/CompanyProjectRepository.java
- src/main/java/com/soda/project/repository/MemberProjectRepository.java
- src/main/java/com/soda/project/repository/ProjectRepository.java
- src/main/java/com/soda/project/service/ProjectService.java
관리자가 프로젝트를 관리하는 기능을 구현하였습니다.
#1 
로그인/권한 없이
- 프로젝트 생성
- 프로젝트 수정
- 프로젝트 삭제
- 프로젝트 전체 조회
- 프로젝트 개발 조회
> [Feature] 프로젝트 기능

- src/main/java/com/soda/request/controller/ReqeustController.java
- src/main/java/com/soda/request/service/RequestService.java
- 승인 요청 상세 조회 API 개발
Closed #20 
- 승인 요청 상세 조회 컨트롤러, 서비스, 리포지토리 메서드 작성
- 없음
> [Feature] 승인 요청 상세 조회 API 개발

- src/main/java/com/soda/request/controller/ReqeustController.java
- src/main/java/com/soda/request/dto/RequestCreateRequest.java
- src/main/java/com/soda/request/service/RequestService.java
- Request 컨트롤러 엔드포인트 팀내에서 정해진 규칙에 맞게 수정
Closed #27
> [Refactor] Request 엔드포인트 수정

- src/main/java/com/soda/request/controller/ResponseController.java
- src/main/java/com/soda/request/dto/response/ResponseDTO.java
- src/main/java/com/soda/request/dto/response/ResponseDeleteResponse.java
- src/main/java/com/soda/request/dto/response/ResponseUpdateRequest.java
- src/main/java/com/soda/request/dto/response/ResponseUpdateResponse.java
- src/main/java/com/soda/request/entity/Response.java
- src/main/java/com/soda/request/error/ResponseErrorCode.java
- src/main/java/com/soda/request/repository/ResponseRepository.java
- src/main/java/com/soda/request/service/ResponseService.java
- 승인요청에 대한 응답 수정/삭제/조회 API 개발
Closed #41 
- 승인요청에 대한 응답(Response)의 수정/삭제/조회 API 구현 완료
> [Feature] 승인요청에 대한 응답 수정/삭제/조회 API 개발

- src/main/java/com/soda/request/dto/response/ResponseDTO.java
- src/main/java/com/soda/request/dto/response/ResponseUpdateResponse.java
- Link관련 컴파일 에러 핫픽스
Closed #44 
- Response 관련 DTO에 Link의 부모엔티티를 만들기 전의 LinkDTO를 사용했었는데 이를 수정하지 않아 컴파일에러가 발생함.
> [HOTFIX] Link관련 컴파일 에러 핫픽스

- src/main/java/com/soda/request/entity/Request.java
- src/main/java/com/soda/request/entity/RequestLink.java
- src/main/java/com/soda/request/entity/Response.java
- src/main/java/com/soda/request/entity/ResponseLink.java
- src/main/java/com/soda/request/service/RequestService.java
- src/main/java/com/soda/request/service/ResponseService.java
- Request, Response 도메인 리팩토링 (테스트가능한 코드, 책임 분리)
#55 
- 최대한 테스트가능한 코드, 순환참조가 없도록 구성하였습니다.
- 다른 도메인 Service 레이어에서 구현해주셔야할 메서드들은 노션에 정리해두었습니다.
> [Refact] Request, Response 리팩토링

- src/main/java/com/soda/article/service/ArticleService.java
- src/main/java/com/soda/project/service/StageService.java
stage 관련 로직을 수정하지 않아 생긴 오류를 해결하였습니다.
closed #66 
- stage service에 `findById` 메서드 추가 후 오류 해결
> [hotfix] stage 오류 해결 

- src/main/java/com/soda/member/service/MemberService.java
- src/main/java/com/soda/project/repository/MemberProjectRepository.java
- src/main/java/com/soda/project/service/CompanyProjectService.java
- src/main/java/com/soda/project/service/MemberProjectService.java
- src/main/java/com/soda/project/service/ProjectService.java
Article service code에서 리팩토링 안된 부분이 있어 다시 리팩토링했습니다.
#57 
- 리스트로 멤버 받아올 일이 있어서 MemberService에 추가만 해두어서 추후에 생성해야 합니다.
- company project, member project 관련 코드를 분리하여 다시 리팩토링했습니다.
> [Refactor] Article service code 리팩토링

- src/main/java/com/soda/article/domain/article/ArticleCreateRequest.java
- src/main/java/com/soda/article/service/ArticleFileService.java
- src/main/java/com/soda/article/service/ArticleLinkService.java
- src/main/java/com/soda/article/service/ArticleService.java
- src/main/java/com/soda/article/service/CommentService.java
- src/main/java/com/soda/member/error/MemberErrorCode.java
- src/main/java/com/soda/project/service/StageService.java
article, article file, article link 각각 책임에 따라 메서드 분리
#57 
- 각 메서드마다 java doc 사용해서 주석을 달았습니다.
- 아직 안 단 service 로직이 있어서 추후에 수정하도록 하겠습니다.
- 기존에는 관리자인 경우/프로젝트에 포함된 경우 두 가지를 한 번에 판단했습니다
- 그런데 각각 service가 다르기 때문에 메서드를 분리하였습니다.
- 기존에는 file과 Link를 한번에 저장하기도 하고, 개수 제한을 하기도 했습니다.
- 적합하지 않다고 판단해 각각 articleFileService, articleLinkService 에 메서드를 분리했습니다.
> [Refactor] Article, Comment 관련 코드 리팩토링

- src/main/java/com/soda/article/service/ArticleService.java
게시글 관련 유효성 검사 로직 수정
closes #80 
- repository 대신 service 참조하면서 메서드 분리를 하닥 유효성 검사를 두 가지로 나누면서 생긴 로직 오류를 수정하였습니다.
- 관리자이거나 프로젝트 해당 멤버이거나, 둘 중 하나를 만족해야 하는데 현재 로직이 모두 만족해야 통과되는 오류가 있었습니다.
- 그래서 로직을 수정하여 해결하였습니다.
```
private void checkIfMemberIsAdminOrProjectMember(String userRole, Member member, Project project) {
boolean isAdmin = memberService.isAdmin(MemberRole.valueOf(userRole));
boolean isProjectMember = memberProjectService.existsByMemberAndProjectAndIsDeletedFalse(member, project);
if (!isAdmin && !isProjectMember) {
throw new GeneralException(ProjectErrorCode.MEMBER_NOT_IN_PROJECT);
}
}
```
-> 이렇게 로직을 수정하였습니다.
> [fix] 게시글 관련 유효성 검사 로직 수정

- src/main/java/com/soda/article/domain/article/ArticleModifyResponse.java
- src/main/java/com/soda/article/domain/comment/CommentUpdateResponse.java
- src/main/java/com/soda/global/config/WebConfig.java
프론트 연동 시 버그 수정
#94 
- 수정 시 id 불일치 오류 때문에 response id 수정
- `WebConfig` 파일에 배포된 프론트 URL 추가
> [Fix] 프론트 연동 시 버그 수정

- src/main/resources/application.yml
> [Fix] 몽고DB ssl연결 옵션 추가

- src/main/resources/application.yml
- 배포서버에서 작동하도록 Redis host와 port추가
Closed #99
> [Fix] Application.yml에 Redis 설정 추가

- src/main/resources/application.yml
[Fix] Application.yml에 Redis 설정 수정
#99
> [Fix] Application.yml에 Redis 설정 수정

- src/main/java/com/soda/project/controller/ProjectController.java
- src/main/java/com/soda/project/repository/MemberProjectRepository.java
- src/main/java/com/soda/project/repository/ProjectRepository.java
- src/main/java/com/soda/project/service/MemberProjectService.java
- src/main/java/com/soda/project/service/ProjectService.java
로그인한 사용자가 참여중인 프로젝트 전체 조회하는 기능을 추가했습니다.
closed #98 
- 로그인한 사용자가 USER인 경우 참여 중인 프로젝트를 전체 조회하는 기능을 추가했습니다.
> [Feature] 사용자 참여 중 전체 프로젝트 조회 기능 추가

- src/main/resources/application.yml
- [Fix] application.yml에 REDIS_HOST 추가
#99
> [Fix] application.yml에 REDIS_HOST 추가

- src/main/resources/application.yml
> [Refactor] ddl-auto 옵션 update로 수정

- src/main/resources/application.yml
> [Refactor] ddl-auto 옵션 create로 수정

- src/main/java/com/soda/global/init/TestDataLoader.java
- src/main/resources/application.yml
- ddl-auto 옵션 update로 재수정 및 테스트용 데이터 세팅하는 코드 주석처리
> [Refact] ddl-auto 옵션 update로 재수정 및 테스트용 데이터 세팅하는 코드 주석처리

- src/main/java/com/soda/member/dto/company/CompanyCreateRequest.java
- src/main/java/com/soda/member/service/AuthService.java
- src/main/java/com/soda/member/service/CompanyService.java
- src/main/java/com/soda/project/controller/TaskController.java
- src/main/java/com/soda/project/domain/stage/StageReadResponse.java
프론트 연결하며 발견한 오류 수정
stage 조회시 task 정렬
company 생성시 ownerName 추가
#111
> [Bug] 프론트 연결하며 발견한 오류 수정

- build.gradle
- src/main/java/com/soda/global/response/GlobalExceptionHandler.java
- src/main/java/com/soda/project/controller/ProjectController.java
- src/main/java/com/soda/project/domain/ProjectCreateRequest.java
- src/main/java/com/soda/project/domain/ProjectCreateResponse.java
- src/main/java/com/soda/project/domain/ProjectDTO.java
- src/main/java/com/soda/project/domain/ProjectListResponse.java
- src/main/java/com/soda/project/domain/ProjectResponse.java
- src/main/java/com/soda/project/domain/ProjectStatusUpdateRequest.java
- src/main/java/com/soda/project/entity/Project.java
- src/main/java/com/soda/project/enums/ProjectStatus.java
- src/main/java/com/soda/project/error/ProjectErrorCode.java
- src/main/java/com/soda/project/repository/ProjectRepository.java
- src/main/java/com/soda/project/service/ProjectService.java
프로젝트 엔티티에 상태(`status`) 필드를 추가하고, 프로젝트 생성 및 수정 시 유효성 검사 로직을 강화했습니다.
또한, 프로젝트 상태를 변경하는 기능을 추가했습니다.
**1. 프로젝트 상태(Status) 관리 추가:**
*   `Project` 엔티티에 `status` 필드 추가 (`ProjectStatus` Enum 타입 사용: CONTRACT, IN_PROGRESS, DELIVERED 등).
*   프로젝트 생성(`ProjectService.createProject`) 시 기본 상태를 `CONTRACT`로 설정하도록 수정.
*   프로젝트 상태 변경 API 엔드포인트 추가 (`PATCH /projects/{projectId}/status` in `ProjectController`).
*   상태 변경 요청 DTO (`ProjectStatusUpdateRequest`) 추가 (`status` 필드 포함, `@NotNull` 검사).
*   상태 변경 로직 구현 (`ProjectService.updateProjectStatus`, `Project.changeStatus`).
*   프로젝트 생성/수정/조회 관련 DTO (`ProjectCreateResponse`, `ProjectDTO`, `ProjectListResponse`, `ProjectResponse`)에 `status` 필드 반영.
**2. 프로젝트 유효성 검사 강화:**
*   **DTO 레벨 검사:**
*   `ProjectCreateRequest` DTO에 `@NotBlank`, `@Size`, `@NotNull`, …
> [Feature] 프로젝트 상태 및 유효성 검사 추가

- build.gradle
- src/main/java/com/soda/global/init/TestDataLoader.java
- src/main/java/com/soda/request/controller/RequestController.java
- src/main/java/com/soda/request/dto/GetRequestCondition.java
- src/main/java/com/soda/request/repository/RequestRepository.java
- src/main/java/com/soda/request/repository/RequestRepositoryCustom.java
- src/main/java/com/soda/request/repository/RequestRepositoryImpl.java
- src/main/java/com/soda/request/service/RequestService.java
- src/main/resources/application.yml
- 승인요청 조건 조회 및 페이지네이션 API 구현하였습니다
#120
- GET projects/{projectId}/requests API 구현하였습니다
- 쿼리파라미터로 stage받을 수 있습니다
- 쿼리파라미터로 status받을 수 있습니다
-  페이지네이션도 가능합니다
- QueryDSL을 활용하여 구현하였습니다.
> [Feature] 승인요청 조건 조회 및 페이지네이션 API 구현

- src/main/java/com/soda/member/entity/Member.java
- src/main/java/com/soda/member/service/AuthService.java
- `Member` 엔티티의 `authId` 필드에 `unique = true` 제약 조건을 추가하여 데이터 무결성을 강화했습니다.
- `AuthService`의 `storeRefreshToken` 메소드에서 Refresh Token 저장 로직을 수정하여 중복 저장을 방지했습니다. 
- 인증 관련 식별자의 유일성을 보장하고, Refresh Token 관리 로직의 정확성을 개선합니다. 
Closes #129
> [Feature] 로그인 속도 개선

- src/main/java/com/soda/global/init/TestDataLoader.java
- src/main/resources/application.yml
- 초기 데이터 세팅 파일 주석처리 및 ddl-auto update로 변경
Closed #135
> [Refact] 초기 데이터 세팅 파일 주석처리 및 ddl-auto update로 변경

- src/main/java/com/soda/global/init/TestDataLoader.java
- src/main/java/com/soda/request/entity/Request.java
- src/main/java/com/soda/request/repository/ResponseRepository.java
- src/main/java/com/soda/request/service/RequestService.java
- src/main/java/com/soda/request/service/ResponseService.java
- src/main/resources/application.yml
- 승인요청에 대한 응답을 삭제해서 응답이 0개가 되는 경우 승인요청 상태가 "PENDING"으로 바뀌지 않는 버그
#139 
- Response 삭제할 때 해당 Request의 isDeleted=false인 Response 개수가 0개면 PENDING 상태로 바꾸도록 하는 코드 추가하여 해결하였습니다.
- 빠른 구현을 위해 일단 JPQL로 구현해놔서 나중에 QueryDSL로 바꾸면 좋을 것 같습니다.
Closed #139
> [Fix] 승인요청에 대한 응답을 삭제해서 응답이 0개가 되는 경우 승인요청 상태가 "PENDING"으로 바뀌지 않는 버그해결

- src/main/java/com/soda/project/controller/ProjectController.java
- src/main/java/com/soda/project/dto/ProjectMemberResponse.java
- src/main/java/com/soda/project/repository/CompanyProjectRepository.java
- src/main/java/com/soda/project/repository/MemberProjectRepository.java
- src/main/java/com/soda/project/service/CompanyProjectService.java
- src/main/java/com/soda/project/service/MemberProjectService.java
- src/main/java/com/soda/project/service/ProjectService.java
프로젝트에 속한 멤버들 조회 기능 추가
Closed #153 
- `/projects/{projectId}/members` 메서드로 멤버 조회 기능을 추가했습니다.
- 파라미터를 추가해 각각 조회할 수 있습니다.
- `members?companyRole=DEV_COMPANY` 등으로 회사 Role에 따라 조회할 수 있습니다.
- `members?companyId=1` companyId를 통해 회사 별로 조회할 수 있습니다.
- `members?memberRole=DEV_MANAGERS` memberRole에 따라 조회할 수 있습니다.
> [Feature] 프로젝트에 속한 멤버들 조회 기능

- src/main/java/com/soda/global/log/dataLog/domain/DataLogCustomRepositoryImpl.java
- 데이터 로그 조회 API 호출 시 페이지네이션의 totalPage가 1로만 반환되는 버그 수정
#171 
- 기존 totalPage가 1로 고정적으로 반환되던 것을 데이터 수, 페이지당 사이즈 수에 따라 정상적으로 반환되게 수정하였음.
- FE에서 코드 더 수정해야 배포환경에서 작동합니다. (바로 수정할 예정입니다.)
Closed #171
> [Fix] 데이터 로그 조회 API 호출 시 페이지네이션의 totalPage가 1로만 반환되는 버그 수정

- src/main/java/com/soda/project/service/ProjectService.java
(그래서 지금 `feature/project-#191` <- `feature/project-!92`로 진행했습니다)
프로젝트 상세 조회 시 유효성 검사 추가
#192 
프로젝트 상세 조회 시,
- 참여 중인 멤버/관리자 : 조회 가능
- 참여 중이 아닌 멤버 : null로 나옴
두 가지 경우의 수가 나오도록 유효성 검사를 추가했습니다.
Closed #192
> [Feature] 프로젝트 상세 조회 시 유효성 검사 추가

- src/main/java/com/soda/article/controller/ArticleController.java
- src/main/java/com/soda/article/dto/article/ArticleSearchCondition.java
- src/main/java/com/soda/article/repository/ArticleRepositoryCustom.java
- src/main/java/com/soda/article/repository/ArticleRepositoryImpl.java
- src/main/java/com/soda/article/service/ArticleService.java
게시글 목록 조회 시, 게시글 검색 기능 추가했습니다.
#185 
- stage별 필터링, keyword로 검색하기 위해 파일 생성했습니다.
- 제목+내용 / 작성자로 검색 가능하도록 `SearchType` enum을 내부에서 지정하였습니다.
- 기존에 List 형식으로 게시글 목록을 조회했는데 이를 페이지네이션으로 수정했습니다.
Closed #185
> [Feature] 게시글 검색 기능

- src/main/java/com/soda/article/controller/ArticleController.java
- src/main/java/com/soda/article/dto/article/ArticleStatusUpdateRequest.java
- src/main/java/com/soda/article/dto/article/ArticleStatusUpdateResponse.java
- src/main/java/com/soda/article/entity/Article.java
- src/main/java/com/soda/article/service/ArticleService.java
'답변완료'로 게시글 상태 변경하는 기능
#241 
- 게시글 작성자가 만족할 만한 답변 혹은 투표 결과가 나올 시 '답변 완료'로 게시글 상태를 변경하는 기능을 추가하였습니다.
> [Feature] 게시글 '답변완료'로 변경하는 기능

- src/main/java/com/soda/article/entity/Article.java
게시글 삭제 오류 해결
#243 
- Article 연관관계 있는 엔티티들도 함께 삭제하려고 했는데 오류가 생겼습니다.
- 그래서 만약 선택사항인 file, link, vote가 Null이 아닌 경우에만 함께 삭제되도록 수정하였습니다.
> [Fix] 게시글 삭제 오류 해결

- src/main/java/com/soda/global/config/AsyncConfig.java
- src/main/java/com/soda/notice/service/EmitterService.java
SSE(Server-Sent Events)를 통한 실시간 알림 전송 로직을 비동기 방식으로 처리하도록 개선합니다. 
알림 전송 작업이 메인 스레드를 블로킹하지 않도록 하여, 
알림을 트리거하는 원래 작업의 응답 속도와 애플리케이션 전반의 반응성을 향상시킵니다.
-   **비동기 처리 설정 (`AsyncConfig.java`):**
*   `@EnableAsync` 어노테이션을 사용하여 Spring의 비동기 기능 활성화했습니다.
*   별도의 스레드 풀(`ThreadPoolTaskExecutor`)을 설정하는 `AsyncConfig` 클래스를 추가했습니다. 
-   **서비스 메서드 비동기화 (`EmitterService.java`):**
*   `EmitterService`의 `sendNotification` 메서드에 `@Async("taskExecutor")` 어노테이션을 추가하여, 
해당 메서드가 설정된 스레드 풀에서 비동기적으로 실행되도록 변경했습니다.
*   비동기 실행 확인을 위해 로그에 현재 스레드 이름을 포함시켰습니다.
Close #183
> [Feature] SSE 알림 전송 비동기 처리 적용

- src/main/java/com/soda/project/service/MemberProjectService.java
- src/main/java/com/soda/project/service/ProjectService.java
프로젝트에 멤버 추가 시 중복 저장 오류 해결
#261 
- 기존 로직에서는 프로젝트에 멤버 추가할 때 (`/projects/{projectId}/members`) 바로 멤버를 추가하도록 구현했었습니다.
- 하지만 기존에 멤버가 존재하는데 멤버의 역할만 변경해서 저장하는 경우 해당 멤버가 중복 저장되는 오류가 있었습니다.
- 그래서 기존 참여 정보가 있는 경우 역할을 변경해 저장하는 로직을 추가하였습니다.
> [Fix] 프로젝트에 멤버 추가 시 중복 저장 오류 해결

- src/main/java/com/soda/request/repository/RequestRepositoryImpl.java
- Request 페이지네이션 시 생성일 기준으로 정렬하되 재승인요청의 경우 부모요청 바로 아래에 순서가 위치하게 수정
#263 
- 기존에 createdAt으로만 정렬을 걸어 FE에서 재승인요청이 제일 위에 출력되는 현상이 포착됨.
- Request 페이지네이션 시 생성일 기준으로 정렬하되 재승인요청의 경우 부모요청 바로 아래에 순서가 위치하게 수정하였음
- 지금은 전체 Request를 조회하고 그 뒤에 필터를 걸고 정렬을 해 Request가 많아지면 성능적으로 치명적일 것임.
- 빠른 구현을 위해 우선 이렇게 구현해두었음. 차후 수정 필요.
> [Refactor] Request 페이지네이션 시 생성일 기준으로 정렬하되 재승인요청의 경우 부모요청 바로 아래에 순서가 위치하게 수정

- src/main/java/com/soda/project/domain/Project.java
프로젝트 생성 시 프로젝트 상태가 null인 오류 해결했습니다.
#308 
- 프로젝트 생성 시 프로젝트 상태가 default로 CONTRACT 가 되도록 수정했습니다.
> [Fix] 프로젝트 생성 시 상태 null 인 오류 해결

- src/main/java/com/soda/project/application/ProjectFacade.java
개발사 추가 API 연동 시 추가 안되는 오류 해결
#310 
- 빈 리스트 형식으로 추가되는 오류를 해결했습니다.
> [fix] 개발사 추가 오류 해결

- src/main/java/com/soda/project/application/stage/request/RequestFacade.java
- 재승인요청 생성시 validate가 비정상적으로 되는 오류 해결
Closed #326
> [Fix] 재승인요청 생성시 validate가 비정상적으로 되는 오류 해결

- src/main/java/com/soda/project/application/stage/article/ArticleFacade.java
- src/main/java/com/soda/project/domain/stage/StageService.java
- src/main/java/com/soda/project/domain/stage/article/Article.java
- src/main/java/com/soda/project/domain/stage/article/ArticleService.java
게시글 수정 시 단계 수정 안되는 버그 해결
#328 
- Article entity의  `updateArticle` 메서드에 stage가 없어서 단계 수정이 안되는 오류가 발생했습니다.
- 해당 메서드와 연관된 facade, service에도 stage를 추가하여 오류를 해결했습니다.
> [Fix] 게시글 수정 시 단계 수정 안되는 버그 해결

- src/main/java/com/soda/project/domain/stage/common/file/S3Service.java
- presignedUrl발급 시 ACL 퍼블릭읽기 설정 추가
#330
> [Feat] presignedUrl발급 시 ACL 퍼블릭읽기 설정 추가

- src/main/java/com/soda/project/domain/stage/common/file/S3Service.java
Reverts Kernel360/KDEV4-SODA-BE#331
- 배포환경에서 예상대로 동작하지 않아 롤백합니다
> Revert "[Feat] presignedUrl발급 시 ACL 퍼블릭읽기 설정 추가"

- src/main/java/com/soda/project/domain/stage/common/file/FileFactory.java
- src/main/java/com/soda/project/domain/stage/common/file/PresignedUrlWithKey.java
- src/main/java/com/soda/project/domain/stage/common/file/S3Service.java
- 파일url에 uuid까지 반환되게 수정
#330 
#확인해야할 사항
- 파일 url을 반환할 때 uuid를 포함하지 않아 없는 url에 접근하여 Access Denied가 떴었습니다.
> [Fix] 파일url에 uuid까지 반환되게 수정

- src/main/java/com/soda/notification/domain/EmitterService.java
[Bug] emitter 시간 만료시 emitter 삭제 로직 추가
#335
> [Bug] emitter 시간 만료시 오류 수정
